### ISSUE TITLE
Cat blocks broken

### ISSUE THREAD

**Issue by ShadowbreakerGD** [TurboWarp/scratch-gui#105]
I found out that catblocks don’t render correctly.
here is the original cat block:
![C9EDFC06-147A-4F6F-8EDA-01E8FE585312](https://user-images.githubusercontent.com/78216950/113883534-3b3cfb80-978c-11eb-9c58-ca620a4debf3.png)
here is the broken Turbowarp cat block:
<img width="255" alt="A6415478-9AE7-4CAC-9C35-A487121DDBC0" src="https://user-images.githubusercontent.com/78216950/113883974-a090ec80-978c-11eb-9af7-3f2a8dcb6d0d.png">

you can obviously see the render fail on the ears.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by TheColaber** [comment]
@GarboMuffin Is this something to move to ScratchAddons/ScratchAddons? The addon should be setting the Blockly constants for the shape of the block to appear like that. Is it something that TW might be doing?

**Comment by GarboMuffin** [comment]
~~I have a rewrite of cat-blocks on top of real Blockly that will fix this and other issues, might pr upstream tomorrow~~ I still have this but it's not completely ideal, will just do a minimal patch for now

@TheColaber please start testing your addons in browsers that aren't Chrome

**Comment by GarboMuffin** [comment]
Upstream merged fix. It will find its way into TW soon
