### ISSUE TITLE
You fixed cat blocks, but there is another problem with them. ._.

### ISSUE THREAD

**Issue by ShadowbreakerGD** [TurboWarp/scratch-gui#112]
[I made an issue about the broken cat block ears](https://github.com/TurboWarp/scratch-gui/issues/105) and you recently fixed them, but now there is another problem:

https://user-images.githubusercontent.com/78216950/114711634-3254a880-9cfd-11eb-81c1-1fd64ca051ad.MP4

The ears break again when place them down. ._.

Anyway, sorry for the troubles.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by cobaltt7** [comment]
Cc @thecolaber

Can't we just steal the code from scratch? Theirs didn't have any bugs. But would that not be compatible as an addon?

**Comment by GarboMuffin** [comment]
Yeah my attempts to fix it broke it

There's an open PR that will fix this. It  will be finished soon.

**Comment by GarboMuffin** [comment]
Upstream merged fix. It will find its way into TW soon
