### ISSUE TITLE
Mascot

### ISSUE THREAD

**Issue by Time-dragon** [TurboWarp/scratch-gui#134]
I'm on ChromeOS, on Chrome 88 or 89 or 90, I don't remember the Chrome version. Maybe remove dango and replace it with Turbopanther? Turbopanther will be modified Neigh Pony.

**Comment by thiyageshvenkat** [comment]
https://partnerdash.google.com/apps/simulator/chromebook#update-your-chromebook?l=en

**Comment by Chaos-emerald** [comment]
@thiyageshvenkat No

**Comment by JaredYoshi** [comment]
hhmmm, good idea

**Comment by Chaos-emerald** [comment]
> hhmmm, good idea

Thanks!

**Comment by JaredYoshi** [comment]
but, why a dango

**Comment by Chaos-emerald** [comment]
> but, why a dango

It was the idea of @GarboMuffin to have it, but I don't want it.

**Comment by thecoder876** [comment]
> but, why a dango

@JaredYoshi it's a scratch meme

**Comment by retronbv** [comment]
> > but, why a dango
> 
> 
> 
> @JaredYoshi it's a scratch meme

No it isn't

**Comment by Chaos-emerald** [comment]
@retronbv It is.

**Comment by retronbv** [comment]
Do you know where and who started the meme?

**Comment by RedGuy12** [comment]
> Do you know where and who started the meme?

Griffpatch's Discord
![image](https://user-images.githubusercontent.com/61329810/116908996-2e83ba00-ac09-11eb-8e30-517d1a29cfef.png)
![image](https://user-images.githubusercontent.com/61329810/116909062-49562e80-ac09-11eb-9a81-491c154a1b90.png)

Then Scratch Addons
![image](https://user-images.githubusercontent.com/61329810/116909127-5e32c200-ac09-11eb-923a-67514bbab2a3.png)

Then ScratchStats
![image](https://user-images.githubusercontent.com/61329810/116909511-ec0ead00-ac09-11eb-913d-3783372809b3.png)

Then Scratch itself
![image](https://cdn.discordapp.com/attachments/751207339545198682/824286065447272478/EKcG4dr7PP.gif)

**Comment by thiyageshvenkat** [comment]
> > Do you know where and who started the meme?
> 
> Griffpatch's Discord
> ![image](https://user-images.githubusercontent.com/61329810/116908996-2e83ba00-ac09-11eb-8e30-517d1a29cfef.png)
> ![image](https://user-images.githubusercontent.com/61329810/116909062-49562e80-ac09-11eb-9a81-491c154a1b90.png)
> 
> Then Scratch Addons
> ![image](https://user-images.githubusercontent.com/61329810/116909127-5e32c200-ac09-11eb-923a-67514bbab2a3.png)
> 
> Then ScratchStats
> ![image](https://user-images.githubusercontent.com/61329810/116909511-ec0ead00-ac09-11eb-913d-3783372809b3.png)
> 
> Then Scratch itself
> ![image](https://camo.githubusercontent.com/51bd72262444252f22631438ad6d3050f287f25afb30263408485b13a20d2929/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3735313230373333393534353139383638322f3832343238363036353434373237323437382f454b63473464723750502e676966)

That's Fake

**Comment by retronbv** [comment]
What is fake about it

**Comment by thiyageshvenkat** [comment]
> What is fake about it

RedGuy12's images are fake. Griffpatch doesn't comment.

**Comment by RedGuy12** [comment]
> > What is fake about it
> 
> RedGuy12's images are fake. Griffpatch doesn't comment.

He does on Discord.

**Comment by thiyageshvenkat** [comment]
> > > What is fake about it
> > 
> > 
> > RedGuy12's images are fake. Griffpatch doesn't comment.
> 
> He does on Discord.

It's not fake actually(I checked scratch  for the project), but what's discord?

**Comment by Chaos-emerald** [comment]
> > > > What is fake about it
> > > 
> > > 
> > > RedGuy12's images are fake. Griffpatch doesn't comment.
> > 
> > 
> > He does on Discord.
> 
> It's not fake actually(I checked scratch for the project), but what's discord?

Some chat thing.

**Comment by thiyageshvenkat** [comment]
> > > > > What is fake about it
> > > > 
> > > > 
> > > > RedGuy12's images are fake. Griffpatch doesn't comment.
> > > 
> > > 
> > > He does on Discord.
> > 
> > 
> > It's not fake actually(I checked scratch for the project), but what's discord?
> 
> Some chat thing.

What do you mean?

**Comment by RedGuy12** [comment]
> > > what's discord?
> > 
> > 
> > Some chat thing.
> 
> What do you mean?

discord is an online chat

**Comment by Emerald-chaos** [comment]
> > > > > > What is fake about it
> > > > > 
> > > > > 
> > > > > RedGuy12's images are fake. Griffpatch doesn't comment.
> > > > 
> > > > 
> > > > He does on Discord.
> > > 
> > > 
> > > It's not fake actually(I checked scratch for the project), but what's discord?
> > 
> > 
> > Some chat thing.
> 
> What do you mean?

It's an online chat.

**Comment by GarboMuffin** [comment]
Not needed
