### ISSUE TITLE
clouddata does not work

### ISSUE THREAD

**Issue by wwj718** [TurboWarp/scratch-gui#139]
### Expected Behavior

open the demo from [wiki](https://github.com/TurboWarp/scratch-gui/wiki/URL-Parameters#cloud_host): https://turbowarp.org/12785898/editor?cloud_host=wss://clouddata.turbowarp.org

### Actual Behavior

clouddata does not work

![image](https://user-images.githubusercontent.com/3153878/116518204-89b06680-a902-11eb-9f8c-553a53d3bc1c.png)

And no websocket connection could be found

### Operating System and Browser

Mac OS 0.13.5 Chrome 90.0

**Comment by GarboMuffin** [comment]
Cloud variables are disabled when you open the editor. Just don't open the editor and they will work.

**Comment by wwj718** [comment]
Thanks
