### ISSUE TITLE
embed colour options

### ISSUE THREAD

**Issue by jeffalo** [TurboWarp/scratch-gui#15]
### feature
so, i was thinking, it would be pretty neat for the embedded player to have some options for things like the colours.

### reason
i'm currently using the embedded player on my website, and it's working great except for it not really fitting well into the design. 
![image](https://user-images.githubusercontent.com/40470736/93665379-417cbc00-fa76-11ea-96c1-8a894dc0f99e.png)
it would be nice to be able to change the turbowarp red (perhaps with a URL query or something) to the pink i'm using in my site. it would also be nice to be able to remove the light blue from thhe top bar in the player or replace the colour with something else

### pros
 more customizable stuff (cooler)

### cons
i guess being able to change the turbowarp red would be bad for the brand of turbowarp?

**Comment by GarboMuffin** [comment]
The blue in the stage header will be removed soon.

Allowing people to change the red to something else would be a lot of work and harm the "brand". If you want to change the colors, then do your own build (https://github.com/TurboWarp/scratch-gui/wiki/Getting-Started) and change $motion-primary and its variants in scratch-gui/src/css/colors.css to something else. That should effect most of the interface.

**Comment by jeffalo** [comment]
👍
