### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Emerald-chaos** [TurboWarp/scratch-gui#150]
![Screenshot 2021-05-03 at 8 04 40 PM](https://user-images.githubusercontent.com/82837930/116947460-d40b4d80-ac4a-11eb-903d-271eb9648912.png)
Made with TurboWarp costume editor and the new opacity slider.

**Comment by GarboMuffin** [comment]
We already have a logo

**Comment by Emerald-chaos** [comment]
> We already have a logo

Tell me please

**Comment by GarboMuffin** [comment]
Its on https://desktop.turbowarp.org/

**Comment by GarboMuffin** [comment]
Or just use the favicon. We don't have or need anything more than that.
