### ISSUE TITLE
Shared Projects Showing as Unshared

### ISSUE THREAD

**Issue by Vivaan-S** [TurboWarp/scratch-gui#157]
### Expected Behavior

_It shows the project and description normally._

### Actual Behavior

_It shows the project as *unshared*_
![Screenshot 2021-05-05 184124](https://user-images.githubusercontent.com/69657903/117230403-d8ae3e00-add1-11eb-82fc-6bb024134956.png)
![Screenshot 2021-05-05 184144](https://user-images.githubusercontent.com/69657903/117230405-d946d480-add1-11eb-842c-2d24ef85f791.png)

### Steps to Reproduce

_Go to https://turbowarp.org/521476421 (may not show as unshared anymore)_

### Operating System and Browser

_My browser / operating system: Windows NT 10.0, Chrome 90.0.4430.93, No Flash version detected_

**Comment by GarboMuffin** [comment]
Usually these things will fix themselves within a few hours

I manually purged the cache server, that should fix whatever you saw
