### ISSUE TITLE
Collaborative Editing when? 😮 

### ISSUE THREAD

**Issue by aetinx** [TurboWarp/scratch-gui#164]
What if Turbowarp had collaborative editing like Figma and Glitch? It'd make coding with other people much easier.

**Comment by GarboMuffin** [comment]
Maybe one day

**Comment by Vivaan-S** [comment]
best idea

**Comment by ghost** [comment]
do we have the resources to make this even possible

**Comment by ghost** [comment]
But how could it keep all the blocks in live record like what that person and this person is doing. Very complicated but possible.
Also too much server usage in some cases when it becomes wide spread.

**Comment by hello-smile6** [comment]
> But how could it keep all the blocks in live record like what that person and this person is doing. Very complicated but possible. Also too much server usage in some cases when it becomes wide spread.

Well, https://github.com/chr15m/bugout could be used to get around the server load issue.

**Comment by GarboMuffin** [comment]
@hello-smile6 I know you're probably just trying to be helpful but you don't need to go around to all the issues and comment something vaguely on topic. It's not helping.

Server load is not a large concern when the entire premise is currently nonexistent

**Comment by hello-smile6** [comment]
> @hello-smile6 I know you're probably just trying to be helpful but you don't need to go around to all the issues and comment something vaguely on topic. It's not helping.
> 
> Server load is not a large concern when the entire premise is currently nonexistent

:(

**Comment by mguinhos** [comment]
I think he should be suggesting that to scratch addons.
Also, live editing could be peer-to-peer, no centralized server is needed

**Comment by hello-smile6** [comment]
> I think he should be suggesting that to scratch addons. Also, live editing could be peer-to-peer, no centralized server is needed

Yes, why not make it P2P? It'd probably only work for users with a browser that supports `showSaveFilePicker()`, because changes would need to be saved in real time. Also, you'd have to somehow make sure that everyone's copies of the SB3 were actually related. If someone created a version control system similar to Git for .sb3 files, it'd probably be a lot easier.

**Comment by hello-smile6** [comment]
> @hello-smile6 I know you're probably just trying to be helpful but you don't need to go around to all the issues and comment something vaguely on topic. It's not helping.
> 
> Server load is not a large concern when the entire premise is currently nonexistent

Could you link to all of my comments? I'll remove them for you.

**Comment by hello-smile6** [comment]
> @hello-smile6 I know you're probably just trying to be helpful but you don't need to go around to all the issues and comment something vaguely on topic. It's not helping.
> 
> Server load is not a large concern when the entire premise is currently nonexistent

Sorry to bother you.
