### ISSUE TITLE
Custom block colors addon "Dark" preset and TurboWarp blocks don't mix

### ISSUE THREAD

**Issue by Time-dragon** [TurboWarp/scratch-gui#178]
### Expected Behavior

Dark color for TurboWarp blocks.

### Actual Behavior

Blinding color still.

### Steps to Reproduce

1. Load TW blocks
2. Use custom block colors addon with Dark preset.
### Operating System and Browser

Chrome OS and Chrome

**Comment by Emerald-chaos** [comment]
Moved to discussion.

**Comment by GarboMuffin** [comment]
no don't do that

**Comment by Time-dragon** [comment]
> no don't do that

Why?

**Comment by GarboMuffin** [comment]
Like I said on the discussion,

GitHub discussions are for discussions.

GitHub issues are for bugs.
