### ISSUE TITLE
embedded player has a thicker border than the normal player

### ISSUE THREAD

**Issue by jeffalo** [TurboWarp/scratch-gui#18]
### Expected Behavior

embedded player's grey border thickness matches the normal player page

### Actual Behavior

the embedded player has a thicker border.
embedded player:
![image](https://user-images.githubusercontent.com/40470736/93854346-dcafa480-fcb5-11ea-85ba-345aba399263.png)
player from the normal page:
![image](https://user-images.githubusercontent.com/40470736/93854373-ec2eed80-fcb5-11ea-9b33-1c95cb840233.png)

### Steps to Reproduce

https://turbowarp.org/ vs https://turbowarp.org/embed.html

### Operating System and Browser

Windows 10 1909 running Chrome

**Comment by GarboMuffin** [comment]
This happens because embeds are *technically* using fullscreen. (see https://turbowarp.org/fullscreen.html and https://turbowarp.org/embed.html)

I'm not sure if this is worth fixing as this is consistent with Scratch.

**Comment by GarboMuffin** [comment]
The large border around players in fullscreen is being removed. This will also remove it from embeds.
