### ISSUE TITLE
Add sa-pause functionality like SA

### ISSUE THREAD

**Issue by just-a-hriday** [TurboWarp/scratch-gui#181]
### Expected Behavior
The TurboWarp addons, which seem to be the same as slightly older versions of SA, should also be able to pause a project by using a custom block named sa-pause. 

### Actual Behavior
When I create a custom block named sa-pause in TurboWarp, it does absolutely nothing! And also, in SA, the sa-pause functionality comes built-in with the pause button addon. TurboWarp has the addon too, and it's enabled by default. But it doesn't have the sa-pause functionality!

### Steps to Reproduce
1. Create custom bock named sa-pause.
2. Click the block (the block, not the definition)
3. Nothing happens!

### Operating System and Browser
Microsoft Edge Beta 91.0.846.19 on WIndows 10 20H2

**Comment by GarboMuffin** [comment]
I believe that addons should not be adding new blocks, especially not blocks that begin with "sa-", and the current implementation is completely incompatible with the compiler anyways.

Edit from the future: The above statement is no longer accurate.
