### ISSUE TITLE
Font licensing issues

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#190]
- SIL OFL used by most fonts is not GPL compatible
 - "Scratch" font (not made by Scratch) is proprietary and we don't have permission to distribute it (open issue in scratch-render-fonts regarding this)

**Comment by hello-smile6** [comment]
Has this been resolved? I can't find a repository for fonts...

**Comment by CST1229** [comment]
> Has this been resolved? I can't find a repository for fonts...

I'm guessing TW just uses [upstream scratch-render-fonts](https://github.com/llk/scratch-render-fonts) as it's just a repository for fonts.

**Comment by hello-smile6** [comment]
> > Has this been resolved? I can't find a repository for fonts...
> 
> I'm guessing TW just uses [upstream scratch-render-fonts](https://github.com/llk/scratch-render-fonts) as it's just a repository for fonts.

Oh. I was confused.
