### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ghost** [TurboWarp/scratch-gui#2]
Add a dark mode.

Considering using another existing dark mode userscript/style for Scratch similar to what we do with the Scratch 3 dev tools.

**Comment by jishnueboyapati** [comment]
aha

**Comment by retronbv** [comment]
![Screenshot 2020-09-15 at 7 10 10 PM](https://user-images.githubusercontent.com/49005044/93273989-316b9080-f787-11ea-9fda-12326048fc24.png)
what about this

[turbowarp-dark.zip](https://github.com/TurboWarp/scratch-gui/files/5228712/turbowarp-dark.zip)

**Comment by GarboMuffin** [comment]
Experimenting: https://experiments.turbowarp.org/dark-mode/

It follows your computer's dark mode preference. Not finalized yet. The red menu bar and splash screen is definitely very jarring. Some colors are a bit broken still.

**Comment by retronbv** [comment]
try my code for the header and dropdowns

**Comment by GarboMuffin** [comment]
I updated https://experiments.turbowarp.org/dark-mode/

I think it looks pretty good. Once I fix the issues with dark mode leaking into the editor (where dark mode is currently not supported), I'll probably merge it.

**Comment by retronbv** [comment]
wait, how do i turn it on?

**Comment by GarboMuffin** [comment]
It follows your system's dark mode preference.

**Comment by retronbv** [comment]
Are you sure bc it’s not working

**Comment by retronbv** [comment]
Nvm

**Comment by GarboMuffin** [comment]
Updated dark mode is now on https://staging.turbowarp.org/

Hoping to make these changes go live some time tomorrow.

**Comment by GarboMuffin** [comment]
Dark mode for the player page is live now.

Will keep this issue open until dark mode is also supported in the editor.

**Comment by retronbv** [comment]
Noice

**Comment by retronbv** [comment]
Dark mode for full screen and embed?

**Comment by GarboMuffin** [comment]
Dark mode will be supported in fullscreen soon

Embeds will also now have a transparent background, so the external site can change the background color of the iframe's container if they want dark mode

**Comment by retronbv** [comment]
Ok **edit:** editor?

**Comment by GarboMuffin** [comment]
The next update of TurboWarp will have a proper dark mode for the editor.

![image](https://user-images.githubusercontent.com/33787854/105565127-d3c5f280-5cea-11eb-9205-89a45c15a214.png)

Not final and some things could certainly be improved, but this is significantly better than not having a dark mode.
