### ISSUE TITLE
URL parameter to control turbo mode

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#20]

**Comment by piano-miles** [comment]
I think they are trying to say that, it would be nice to provide a URL parameter to control turbo mode. Something like either ?turbo or ?turbomode.

**Comment by GarboMuffin** [comment]
Can now use ?turbo: https://turbowarp.org/?turbo#15832807

https://github.com/TurboWarp/scratch-gui/wiki/URL-Parameters
