### ISSUE TITLE
Remove the editor warning message

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#211]
![image](https://user-images.githubusercontent.com/33787854/120142950-dbb80680-c1a4-11eb-97de-e5d524bdea70.png)

let's find a way to remove this

 - restore points were cobbled together in a couple days when editor crashes were a real problem (they aren't so much anymore), they could be removed or a better version can be made
 - reminder about warp timer is meaningless to most people

**Comment by kaneryu** [comment]
(sorry for commenting on a closed topic) Please don't remove. On chromebook, the power button is right above the backspace button, and a real issue is double tapping the power button, which shuts down your pc, without asking.
