### ISSUE TITLE
Scratch 3.0 Extensions Unable to Load From .sb3 File.

### ISSUE THREAD

**Issue by mrsproutt** [TurboWarp/scratch-gui#231]
When I try to import a project with a custom extension to Turbowarp it gives me the error:

"The project file that was selected failed to load"

When the project finally loads it only shows the variables on the stage and deletes all your code and sprites. Could you please fix this glitch?

**Comment by GarboMuffin** [comment]
You have to load the project using the same link that you used to save it.

**Comment by GarboMuffin** [comment]
If you are doing that already, attach the project file (might have to put it in a zip) and the URL of the extension you're trying to use

**Comment by GarboMuffin** [comment]
Closing under the assumption you weren't using the same link to open it that you used to save it. Comment if that's not the case.
