### ISSUE TITLE
I have an idea

### ISSUE THREAD

**Issue by YOYITsM3M8** [TurboWarp/scratch-gui#24]
This is for the website and I don’t see a repo for it so it goes here now. Add Easter eggs!

1. Add “pirate language” and “meow” to the languages
2. Some other stuffs

**Comment by YOYITsM3M8** [comment]
@GarboMuffin garbo plz think about this

**Comment by GarboMuffin** [comment]
I'm not going to be adding easter eggs.

**Comment by YOYITsM3M8** [comment]
y

**Comment by GarboMuffin** [comment]
This is a serious tool that people use to get things done. It's not a toy. I don't have time to go around adding little jokes all over the place, especially when they inevitably break something important or result in 300 line merge conflicts pulling from upstream.

Translations are currently one of the single largest items in the massive (12MB!) JavaScript bundle. At least those translations actually benefit people, but a pirate language is a useless gimmick that no one would find or benefit from.

**Comment by YOYITsM3M8** [comment]
i would benefit from pirate language

but all jokes aside

ok
