### ISSUE TITLE
debugger logs window has no darkmode styling

### ISSUE THREAD

**Issue by cobaltt7** [TurboWarp/scratch-gui#241]
![image](https://user-images.githubusercontent.com/61329810/122451379-ad407680-cf6d-11eb-9d87-73a20f355b24.png)

**Comment by retronbv** [comment]
It's not broken, the styles just don't apply.

**Comment by GarboMuffin** [comment]
Debugger will finally have dark mode in the next update

![image](https://user-images.githubusercontent.com/33787854/170849213-6b149790-6483-4398-be00-3304e0aa996f.png)
