### ISSUE TITLE
Website does not load when stage size is a decimal number

### ISSUE THREAD

**Issue by just-a-hriday** [TurboWarp/scratch-gui#252]
### Expected Behavior
The size should round itself. It would also be fine if it asked the user to make it an integer. 

### Actual Behavior
It just loads forever - no crashes, no warnings, it doesn't even tell the user what's going wrong!

### Steps to Reproduce

1. Go into advanced settings
2. Change the stage width or height (or both) to a decimal number.
3. Click the cross
4. Click OK.

**OR**

1. Copy `https://turbowarp.org/?size=479.9x359.9` into the adress bar.

### Operating System and Browser
Microsoft Edge Beta 91.0.864.19 on Windows 10 20H2 64-bit

**Comment by GarboMuffin** [comment]
Sorry for missing this, TurboWarp/scratch-svg-renderer is not a repository I actively monitor.

**Comment by just-a-hriday** [comment]
> Sorry for missing this, TurboWarp/scratch-svg-renderer is not a repository I actively monitor.

No problem 😉
