### ISSUE TITLE
Controller support

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#26]
Maybe we can add support for controllers, game pads and things like that.

Not clear what the blocks for this would look like.

**Comment by thiyageshvenkat** [comment]
That would be pretty cool.

**Comment by GarboMuffin** [comment]
A beta version of this will be included in the next update (today/tomorrow) with a disabled-by-default addon called "Gamepad support"

**Comment by thiyageshvenkat** [comment]
> A beta version of this will be included in the next update (today/tomorrow) with a disabled-by-default addon called "Gamepad support"

Do you think having screen x and screen y turbowarp blocks will be useful?

**Comment by GarboMuffin** [comment]
> 
> 
> > A beta version of this will be included in the next update (today/tomorrow) with a disabled-by-default addon called "Gamepad support"
> 
> Do you think having screen x and screen y turbowarp blocks will be useful?

Not sure what you mean? If you're trying to the size of the stage when custom stage sizes are used, then that's already possible: https://scratch.mit.edu/projects/475562469/

**Comment by thiyageshvenkat** [comment]
> > > A beta version of this will be included in the next update (today/tomorrow) with a disabled-by-default addon called "Gamepad support"
> > 
> > 
> > Do you think having screen x and screen y turbowarp blocks will be useful?
> 
> Not sure what you mean? If you're trying to the size of the stage when custom stage sizes are used, then that's already possible: https://scratch.mit.edu/projects/475562469/

Finding out the screen x and y of your device.

**Comment by thiyageshvenkat** [comment]
I saw the game pad support in the desktop turbowarp and online turbowarp. I don't have a game pad to try it.
