### ISSUE TITLE
Eu não sei traduzir o TurboWarp

### ISSUE THREAD

**Issue by Simocas240** [TurboWarp/scratch-gui#279]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by CST1229** [comment]
According to Google Translate, this is the title in English:
> I can't translate TurboWarp

**Comment by GarboMuffin** [comment]
This issue tracker uses English. I don't understand what is being asked even with a translator, sorry.
