### ISSUE TITLE
Add Javascript Exporting

### ISSUE THREAD

**Issue by aetinx** [TurboWarp/scratch-gui#29]
Since Turbowarp compiles Scratch projects to Javascript, can we download projects as Javascript?

Add HTMLier-like HTML download too?

**Comment by GarboMuffin** [comment]
> Since Turbowarp compiles Scratch projects to Javascript, can we download projects as Javascript?

https://github.com/TurboWarp/scratch-gui/wiki/How-do-I-copy-the-JavaScript

> Add HTMLier-like HTML download too?

There's an early experiment for that: https://garbomuffin.github.io/p3/

**Comment by GarboMuffin** [comment]
Closing as https://packager.turbowarp.org/ exists and leopard should be used for getting readable JS from Scratch

**Comment by aetinx** [comment]
> Closing as https://packager.turbowarp.org/ exists and leopard should be used for getting readable JS from Scratch

You should know that Leopard doesn't work very well.

**Comment by GarboMuffin** [comment]
If you want readable JavaScript then you will give up some compatibility.
