### ISSUE TITLE
Extension doesn't load

### ISSUE THREAD

**Issue by stretch07** [TurboWarp/scratch-gui#291]
### Expected Behavior

Extension loads

### Actual Behavior

Doesn't load: this is the error: NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://among-maps.github.io/Among-Maps/extension.js' failed to load.

### Steps to Reproduce

Add extension https://among-maps.github.io/Among-Maps/extension.js

Don't understand why this is even a network error, my wifi's good...

### Operating System and Browser

ChromeOS Version 93.0.4577.15 (Official Build) beta (64-bit)

**Comment by GarboMuffin** [comment]
You have a SyntaxError: you forgot to close the class with a `}`

Not sure if that error message can be improved because I think that's all the information we get from the browser :(
