### ISSUE TITLE
Bug "Dragging Sprites"

### ISSUE THREAD

**Issue by Medericoder** [TurboWarp/scratch-gui#292]
I don't press anything !

https://user-images.githubusercontent.com/80577386/127779716-48444a96-8454-41b4-84ac-c03a806e1c92.mp4

**Comment by GarboMuffin** [comment]
- What version are you using? (Question mark icon -> about -> in the title)
 - Does it happen outside of fullscreen mode?
 - Does it happen with all addons disabled?

**Comment by Medericoder** [comment]
> * What version are you using? (Question mark icon -> about -> in the title)
The newest one

> * Does it happen outside of fullscreen mode?
Twice

> * Does it happen with all addons disabled?
I didn't try, and I can't today, I don't have my computer for the next 10 hours

(I'm French, excuse my English)

**Comment by PenguinLover1123** [comment]
> > * What version are you using? (Question mark icon -> about -> in the title)
> >   The newest one
> 
> > * Does it happen outside of fullscreen mode?
> >   Twice
> 
> > * Does it happen with all addons disabled?
> >   I didn't try, and I can't today, I don't have my computer for the next 10 hours
> 
> (I'm French, excuse my English)

You were ninjaed

**Comment by GarboMuffin** [comment]
Does this still happen?

**Comment by GarboMuffin** [comment]
If this still happens, please comment
