### ISSUE TITLE
Transparency for embeds?

### ISSUE THREAD

**Issue by micahlt** [TurboWarp/scratch-gui#30]
## Feature suggestion

Currently, all embeds have a white background.

![image](https://user-images.githubusercontent.com/28816297/98282849-6f558b80-1f64-11eb-9918-81605fcd1d60.png)

It would be incredible to have embeds use a transparent background.  This would create a much more unified effect in external applications.  Something like this: 

![image](https://user-images.githubusercontent.com/28816297/98283035-ab88ec00-1f64-11eb-992b-be11305efaf5.png)

**Comment by GarboMuffin** [comment]
See if this will work: https://experiments.turbowarp.org/transparent-embeds/embed.html#1

**Comment by GarboMuffin** [comment]
If that works I'll push it to production sometime this weekend

**Comment by micahlt** [comment]
That works perfectly!

**Comment by GarboMuffin** [comment]
turbowarp.org/embed.html is now transparent

**Comment by micahlt** [comment]
@GarboMuffin Hm... You said you pushed this to production, but I'm still getting a white background when embedding with the normal URL (not the experiments one).

**Comment by GarboMuffin** [comment]
It seems to work fine for me here: https://turbowarp.org/static/embedtest.html

Are you sure you're embedding the embed page and not something else and that you have allowtransparency=true?

**Comment by micahlt** [comment]
Hmm... this is weird.  I'm using TurboWarp with Ionic Framework.  It must be an Ionic issue because when `prefers-color-scheme` is `light`, the background _is_ transparent.  However, when it's `dark` it is white.  Huh.  CSS looks fine after inspection...

**Comment by GarboMuffin** [comment]
That is very strange, especially because the embed page doesn't even use prefers-color-scheme beyond the loading screen. Could be a framework issue, though that wouldn't explain why experiments.turbowarp.org/transparent-embeds works but not turbowarp.org (I assume this is the case?)

I've temporarily removed the big warning message from transparent-embeds until this is resolved. I still intend to remove that experiment entirely at some point.

**Comment by micahlt** [comment]
After checking again, the `transparent-embeds` URL performs the same way as the normal one - sorry that I jumped to that conclusion!  Yes, I assume it's a framework issue though it makes very, very little sense because I **cannot** get it to work, even by setting all backgrounds to `transparent` with Devtools.  Huh.

**Comment by micahlt** [comment]
Here's how it performs with a wrapper `div`'s background set to `green`: 
### `prefers-color-scheme: light`
![image](https://user-images.githubusercontent.com/28816297/104968505-ad7f1a80-59ab-11eb-8615-87bce99a574e.png)

### `prefers-color-scheme: dark`
![image](https://user-images.githubusercontent.com/28816297/104968555-ca1b5280-59ab-11eb-87cd-ad473d34b5b3.png)

**Comment by GarboMuffin** [comment]
If it's a framework issue, then I don't think there's anything I can do.
