### ISSUE TITLE
Bug: Dynamic menu doesn't update

### ISSUE THREAD

**Issue by MikeDev101** [TurboWarp/scratch-gui#305]
### Expected Behavior

I expect this block:

![block_8_22_2021-11_06_57 AM](https://user-images.githubusercontent.com/12957745/130360108-bc0692de-a2f6-4adc-b0f2-b3bfaec6cf64.png)
to display one of two items. My extension fetches a list of server addresses immediately after the extension is loaded, and the server list is updated. From there, the dynamic menu item should update, and display those items.

### Actual Behavior

The server list is fetched, as the value of this block:

![block_8_22_2021-11_12_52 AM](https://user-images.githubusercontent.com/12957745/130360335-55ccdc56-d550-4fe5-b985-9a971889909c.png)
is updated, but the dynamic menu stays empty. 

### Steps to Reproduce

Step 1: Use this [URL](https://turbowarp.org/editor?extension=https://mikedev101.github.io/cloudlink/B3-0.js)
Step 2: Wait for fetches to serverlist.json finish
Step 3: Check if dynamic menu updates (which it isn't)

To compare results, use this [URL](https://sheeptester.github.io/scratch-gui/?url=https://mikedev101.github.io/cloudlink/B3-0.js) and refresh only once

### Operating System and Browser

Windows 10 20H2 (OS Build 19042.1110), Chrome 91.0.4472.124 (Official Build) (64-bit)

### Note

This was working fine about a day ago. It looks like an update broke dynamic menus.

**Comment by GarboMuffin** [comment]
I tried to rewrite the extension sandbox for improved security and API access, but I guess something got broken. Should work again now

**Comment by GarboMuffin** [comment]
it appears it's still broken

**Comment by MikeDev101** [comment]
Looks like it's a hit-or-miss sort of deal. Seems after a refresh it updates, but sometimes it doesn't. Looks like it's either a bug with dynamic menus in general or I'm overlooking a rookie mistake in my extension...

**Comment by GarboMuffin** [comment]
I think the problem is that dynamic menus in custom extensions actually just don't work. I believe right now your `servermenu` is just a static menu that will never get updated, but sometimes you get lucky and the serverlist.json fetch completes before Scratch sets up the menus.

I think for now it might be best to hardcode serverlist.json in the extension's source.

You could also try to avoid calling Scratch.extensions.register until after the fetch has completed, but I think that will cause issues when trying to load projects.

I'll see if there's anything that can be done to improve this

**Comment by MikeDev101** [comment]
> I think for now it might be best to hardcode serverlist.json in the extension's source.

That's what I might need to do, or I might need to implement a manual list refresh command

> You could also try to avoid calling Scratch.extensions.register until after the fetch has completed, but I think that will cause issues when trying to load projects.

Did that during the development of the feature, it slows down the extension loading period, but regardless it still didn't update reliably

**Comment by GarboMuffin** [comment]
Custom extension menus currently cannot be dynamic (technical limitation, not trivial to fix), so you should just hardcode the list

**Comment by MikeDev101** [comment]
> Custom extension menus currently cannot be dynamic (technical limitation, not trivial to fix), so you should just hardcode the list

It appears to be "functional" but thanks for the tip
let me know if it becomes a thing in the future

**Comment by GarboMuffin** [comment]
you may be interested in following #633 

I'm actually not entirely sure if dynamic menus will work with those upcoming changes, but they might affect you in other (probably good) ways

**Comment by MikeDev101** [comment]
Various members from @meower-media-co alerted me beforehand. Looking forward to it!

**Comment by GarboMuffin** [comment]
Dynamic menus will be limited to unsandboxed extensions for technical reasons -- the item generator needs to be synchronous which is not possible with the sandbox.
