### ISSUE TITLE
Suggestion: Make max changed FPS be 1000 FPS

### ISSUE THREAD

**Issue by PenguinLover1123** [TurboWarp/scratch-gui#306]
Raymarcher and prime number detector projects would really benefit from this. They would be **even** faster at max FPS.

**Comment by PenguinLover1123** [comment]
Anyone here?

**Comment by Samq64** [comment]
1. No computer can run at 1000 FPS, I think 250 is the maximum for even high-end machines.
 2. Even if you use 250 FPS (maximum) the project will still run at 60 on most computers.
 3. I don't think higher FPS is any better than turbo mode or run without screen refresh for your case.

**Comment by GarboMuffin** [comment]
Turbo mode and run w/o screen refresh will do more for performance than higher framerates.

The JS spec says that setInterval can't run faster than 250 anyways, so it would make no difference.
