### ISSUE TITLE
Make a topic for TurboWarp on scratch forums

### ISSUE THREAD

**Issue by PenguinLover1123** [TurboWarp/scratch-gui#309]
Please . . .

**Comment by PenguinLover1123** [comment]
Bump (do bumps work on github?)

**Comment by cobaltt7** [comment]
Bumps do not work on github and are considered spam.


________________________________

**Comment by its-pablo** [comment]
I don't think this is something turbowarp could do, nor something Scratch is willing to do.
Perhaps this could be done with scratch-addons, however it would be server-side and I doubt many people would use it :/

**Comment by CST1229** [comment]
> 
> 
> I don't think this is something turbowarp could do, nor something Scratch is willing to do.
> Perhaps this could be done with scratch-addons, however it would be server-side and I doubt many people would use it :/

What? This is literally just making a topic on the forums.

**Comment by Nekosis** [comment]
> > I don't think this is something turbowarp could do, nor something Scratch is willing to do.
> > Perhaps this could be done with scratch-addons, however it would be server-side and I doubt many people would use it :/
> 
> What? This is literally just making a topic on the forums.

I think that @its-pablo thought OP meant making a forum topic within a project.

**Comment by hello-smile6** [comment]
> > > I don't think this is something turbowarp could do, nor something Scratch is willing to do.
> > > Perhaps this could be done with scratch-addons, however it would be server-side and I doubt many people would use it :/
> > 
> > 
> > What? This is literally just making a topic on the forums.
> 
> I think that @its-pablo thought OP meant making a forum topic within a project.

That'd be cool!

**Comment by GarboMuffin** [comment]
A forum thread has been created, only 2 years behind schedule

https://scratch.mit.edu/discuss/topic/641251/
