### ISSUE TITLE
Reloading project without interrupting user

### ISSUE THREAD

**Issue by aryanbaburajan** [TurboWarp/scratch-gui#32]
A button on the navbar, which when pressed, will reload the project from its source (scratch.mit.edu/projects/00000000) But without the **"Loading"** screen. This isn't really a necessary feature, but will be useful for anyone who's using TurboWarp for their own project (Like me). 

Or, is there any way to use a chrome extension to reload without the **"Loading"** Screen
Thanks!

**Comment by GarboMuffin** [comment]
Even if a refresh button is added, you will still see the "Loading project ..." screen because, well, it has to go download the project again. I don't know how useful a dedicated button for this would be.

**Comment by aryanbaburajan** [comment]
The main use of this was to enable users to load without the loading screen in a way that they won't even know but the downside is that this may lead to any bug/glitch. And yes, this feature wont be much of a use, at least i don't think so.

**Comment by GarboMuffin** [comment]
Reloading projects without showing a loading screen will not be implemented because I don't think it will be that useful.
