### ISSUE TITLE
On the translate extension

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#322]
Scratch's translate service has been down for an extended period of time and we may be sort of responsible (not entirely sure on the details)

As a temporary measure to ensure that projects that use the translate block continue to work normally and to avoid spamming Scratch's servers, the translate blocks have been modified to just return the text that gets put into it without translation instead of making a request to a server that's probably going to be down and get stuck for 10 seconds. It will likely stay like this for the foreseeable future, even after Scratch's translate server is fixed.

Projects that abused the translate extension to detect online status may or may not be affected. Those projects were a hack that shouldn't have existed and may be a significant contributing factor for the API being broken, so I'm not too concerned about breaking those projects. Please stop making them.

[note from the future: when this issue was opened, the server had been almost always down for several days. It seems to be up now, we are considering how to move forward.]

**Comment by Paradockz** [comment]
Look like I making some random crap to make broken English using the translate blocks and getting banned because it, maybe caused this issue for a sec.

**Comment by CST1229** [comment]
> 
> 
> Look like I making some random crap to make broken English using the translate blocks and getting banned because it, maybe caused this issue for a sec.

A developer said that someone on TurboWarp was also spamming the translate servers with stuff like "123.456", "654.321", etc.

**Comment by GarboMuffin** [comment]
~~Within the next few days I'll start logging what strings people are translating using that extension to see if caching is viable. Hopefully within a week everything will start working again.~~ hasn't happened yet

**Comment by GarboMuffin** [comment]
... and now Scratch's translate server is down again. At least we know this time it's not our fault.

I haven't been logging the messages being translated yet, only the # of requests, which varies from 3 to 30,000 requests per hour.

**Comment by GarboMuffin** [comment]
89% of all translate requests are just random numbers, presumably for projects to try to detect internet connectivity (66014 of 73945 recorded requests match `/^\d+(\.\d+)?$/`) Those are trivial to ignore before sending to Scratch.

Hopefully translate will be back soon because it seems caching will work.

**Comment by GarboMuffin** [comment]
The translate extension works now.
