### ISSUE TITLE
Disabled scratch-blocks context menu items look too similar to enabled ones in dark mode

### ISSUE THREAD

**Issue by mxmou** [TurboWarp/scratch-gui#336]
### Expected Behavior

In both light and dark mode, it would be easy to see the difference between enabled and disabled options in the scratch-blocks context menu.

### Actual Behavior

In dark mode, the colors are very similar: `#eeeeee` for enabled items and `#cccccc` for disabled ones.

### Steps to Reproduce

Set the theme to dark and right click the workspace.

### Operating System and Browser

Edge 93 on Windows 10

**Comment by GarboMuffin** [comment]
It will now look like this

![image](https://user-images.githubusercontent.com/33787854/134778550-ec37aa81-04d9-46f3-9c61-0d45c79d6c96.png)
