### ISSUE TITLE
Allow custom extensions to render arbitrary things on the stage

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#338]
Since custom extensions are based on <iframe> now, we could probably stack them on top of the canvas to allow some interesting possibilities.

**Comment by GarboMuffin** [comment]
#633 is the approach we will be going with. Custom extensions with that mechanism will be able to render whatever they want on the stage.

**Comment by David-Orangemoon** [comment]
I wrote an unsandboxed extension that does smth similar except it just overwrites whats on the stage this might be useful.
