### ISSUE TITLE
A way to tell if a gamepad is being used

### ISSUE THREAD

**Issue by ghost** [TurboWarp/scratch-gui#341]
i.e: to show the correct controls in a tutorial

**Comment by GarboMuffin** [comment]
We are hesitant to add blocks that affect project behavior, but it will be considered

**Comment by GarboMuffin** [comment]
The unsandboxed gamepad extension does support this: https://extensions.turbowarp.org/

**Comment by GarboMuffin** [comment]
https://extensions.turbowarp.org/
