### ISSUE TITLE
Extension won't run, when I think it's completely fine, without errors.

### ISSUE THREAD

**Issue by josiauh** [TurboWarp/scratch-gui#351]
### Extension Name (planned)
Josiah Testing 
## Actual name
Josiah

### What's supposed to happen:
It would run completely fine.

### What actually happens:
Not able to run.

### My code
```js
// We use class syntax to define our extension object
// This isn't actually necessary, but it tends to look the best

class JosiahExtension {
    /**
     * Scratch will call this method *once* when the extension loads.
     * This method's job is to tell Scratch things like the extension's ID, name, and what blocks it supports.
     */
    getInfo() {
      return {
        // `id` is the internal ID of the extension
        // It should never change!
        // If you choose to make an actual extension, please change this to something else.
        // Only the characters a-z and 0-9 can be used. No spaces or special characters.
        id: 'josiahsextensionjs',
  
        // `name` is what the user sees in the toolbox
        // It can be changed without breaking projects.
        name: 'Josiah',
  
        blocks: [
          {
            // `opcode` is the internal ID of the block
            // It should never change!
            // It corresponds to the class method with the same name.
            opcode: 'hello',
            blockType: Scratch.BlockType.REPORTER,
            text: 'Hello, world!'
          },
          {
            opcode: 'dev',
           blockType: Scratch.BlockType.REPORTER,
           text: 'Developer and How to make this'
          },
          {
            opcode: 'closeto',
            blockType: Scratch.BlockType.BOOLEAN,
            text: '[NumF] is close to [NumS]',
            arguments: {
                NumF: {
                    type: Scratch.ArgumentType.NUMBER,
                    defaultValue: 1
                },
                NumS: {
                    type: Scratch.ArgumentType.NUMBER,
                    defaultValue: 2
                }
            }
          },
        ]
      };
    }
  
    /**
     * Corresponds to `opcode: 'hello'` above
     */
    hello() {
      // You can just return a value: any string, boolean, or number will work.
      // If you have to perform an asynchronous action like a request, just return a Promise.
      // The block will wait until the Promise resolves and return the resolved value.
      return 'Hello, world!';
    }
    dev() {
      return 'Josiah, Mar10Josh. Visit the turbowarp docs to make one.'
    }
    closeto(args) {
        return args.NumF == args.NumS - 1 || args.NumF == args.NumS - 2 || args.NumF == args.NumS + 1 || args.NumF == args.NumS + 2
    }
  }
  
  // Call Scratch.extensions.register to register your extension
  // Make sure to register each extension exactly once
  Scratch.extensions.register(new JosiahExtension());
```
### Links used to load
https://files.fm/pa/josiahreybacsal/josiah.js/josiah.js (fail)
localhost and ip (fail)
mar10josh.github.io/josiahtwext/josiah.js and with https:// too (fail until BlockType fix)
### I tried this on console, here's a result explanation:
Scratch wasn't identified, maybe it's something to do with the blocks?

**Comment by TheColaber** [comment]
It seems the url sent shows:
{"error":"Target user is not a subscriber. File access by path is a subscriber only feature!"}
Which is likely the problem

**Comment by josiauh** [comment]
> It seems the url sent shows: {"error":"Target user is not a subscriber. File access by path is a subscriber only feature!"} Which is likely the problem

Thanks! I will find another file hosting website. I'll see if that works.

**Comment by josiauh** [comment]
> It seems the url sent shows: {"error":"Target user is not a subscriber. File access by path is a subscriber only feature!"} Which is likely the problem

I tried localhost and the ip thingy but not working, what do you suggest?

**Comment by GarboMuffin** [comment]
github pages

**Comment by josiauh** [comment]
> github pages

Mkay, I'll try

**Comment by josiauh** [comment]
> github pages

Can you try this out? https://mar10josh.github.io/josiahtwext/josiah.js

**Comment by josiauh** [comment]
> > github pages
> 
> Can you try this out? https://mar10josh.github.io/josiahtwext/josiah.js

Actually, it won't work, Maybe the code has a bit of error.

**Comment by GarboMuffin** [comment]
If you open the JS development console you'll see `TypeError: Scratch.Blocktype is undefined`, because you did `Scratch.Blocktype` instead of `Scratch.BlockType` somewhere.

Anyways, not a TW bug, so closing. Keep commenting here if you'd like

**Comment by josiauh** [comment]
Ooooh sorry
