### ISSUE TITLE
Please Not Allow to download or see inside unshared projects

### ISSUE THREAD

**Issue by ghost** [TurboWarp/scratch-gui#359]
I am asking turbowarp to add a feature so that peoples cannot download the project or see inside the project. They should only be able to test out the project. 
I am asking for this feature as there are nowadays cases of people stealing others projects and not giving credits to the creators and often annoying them. 
I think this would be useful for beta testing / work in progress like purposes so that the project wouldn't be taken.

**Comment by MrBrightCosmos** [comment]
yes I will working in scratch addons there will be a option this a a pre-release then turbowarp we remove the feature that we can't download the project

**Comment by GarboMuffin** [comment]
Tell the Scratch Team to fix the API. That's the only real solution.

https://docs.turbowarp.org/unshared-projects#why-not-fix
