### ISSUE TITLE
Standalone Desktop App

### ISSUE THREAD

**Issue by techboyg5** [TurboWarp/scratch-gui#36]
How about making a standalone desktop app that works oflfine?

[Electron](https://www.electronjs.org/) would be good for this.

**Comment by GarboMuffin** [comment]
I think I'll have some good news for you soon

**Comment by techboyg5** [comment]
> I think I'll have some good news for you soon

???

**Comment by GarboMuffin** [comment]
I worked on this last night. I have a working prototype. I haven't uploaded binary builds yet because there's some bugs and licensing issues that must be resolved first.

**Comment by techboyg5** [comment]
> I worked on this last night. I have a working prototype. I haven't uploaded binary builds yet because there's some bugs and licensing issues that must be resolved first.

Screenshot?

**Comment by retronbv** [comment]
Nice

**Comment by techboyg5** [comment]
> I worked on this last night. I have a working prototype. I haven't uploaded binary builds yet because there's some bugs and licensing issues that must be resolved first.

Cool! Some suggestions:
* Everything should be packaged.
* It should load straight to the editor, skipping the "TurboWarp is a Scratch mod..." page.
* Use Electron, and use it's APIs when possible for better integration.

**Comment by GarboMuffin** [comment]
I hope to release v0.0.1 tomorrow. The only blocker right now is adding a primitive update checker.

Currently the builtin sprite and sound library won't work offline. I hope to get that and some other improvements in v0.0.2.

**Comment by GarboMuffin** [comment]
v0.0.1 released https://github.com/TurboWarp/desktop/releases
