### ISSUE TITLE
Turbowarp crashing on iOS when too many sprites are in the project

### ISSUE THREAD

**Issue by Boem22** [TurboWarp/scratch-gui#363]
Turbowarp crashing on iOS, when too many sprites need to be loaded

**Comment by Boem22** [comment]
any project where +500 costumes need to be loaded

**Comment by junaayd123** [comment]
I don't think iOS can handle 500 or more costumes in scratch.

**Comment by Boem22** [comment]
> I don't think iOS can handle 500 or more costumes in scratch.

some devices can, some lower end devices can't

**Comment by GarboMuffin** [comment]
It depends on the project

There's been some significant memory improvements to costumes recently. If a certain project still has issues, open a new issue with more information about that project
