### ISSUE TITLE
Broken X and Y

### ISSUE THREAD

**Issue by Dieforrobux** [TurboWarp/scratch-gui#37]
### Expected Behavior
Not allowing to go past max x and max  y.

### Actual Behavior
Going past the limits(X max 568 Y max 456)

### Steps to Reproduce
1. Search up on scratch " MathMathMath ".
2. Click on " 3D Graphics Part 1 " ( Has to be by MathMathMath.)
3.Look at remixes. There should be one that has fixed on it, click on it.
4.Scroll down. There should be a studio with the same thumbnail. Click on it.
5.Do all the tutorials. 
6 . Now move to the left or right a lot and there it is! Glitch reproduced.

### Operating System and Browser

_Chrome Book, Version 87.0.4280.109_

**Comment by GarboMuffin** [comment]
Please just give me a link to a project that is broken, I don't have time to hunt down some project in a studio.

**Comment by Dieforrobux** [comment]
# Long answer
Go to this project: https://turbowarp.org/324049414 and then just hit right arrow until you see " Now you can move like a FPS game! " then see inside, go to sprite "Pen1 and your done.It should look like this: 
![download - 2021-01-05T121752 875](https://user-images.githubusercontent.com/71724356/103677251-0f716600-4f50-11eb-9875-0ba4becedbac.png). Sadly github can't show it so it can only show you the " Now you can move like a FPS game! "
# Short answer
Go here: https://turbowarp.org/324049414/editor and look at Pen1 (sprite.) move to left or right a lot and x is broken.

Weird thing is that it also happens in scratch

**Comment by GarboMuffin** [comment]
> Weird thing is that it also happens in scratch

Scratch bug, not a TurboWarp bug.

**Comment by GarboMuffin** [comment]
Probably a project bug actually.

**Comment by Dieforrobux** [comment]
Ok then
