### ISSUE TITLE
No warning should appear when embedding TurboWarp editor

### ISSUE THREAD

**Issue by techboyg5** [TurboWarp/scratch-gui#38]
When you embed the TurboWarp _editor_, a warning appears blocking the parent page.

That warning should be removed.

**Comment by GarboMuffin** [comment]
Removed alert

**Comment by lafkpages** [comment]
I'm trying to embed the editor but there are no docs on this. If I embed `/` or `/editor` the warning still shows up and the page never loads.

**Comment by GarboMuffin** [comment]
Please read the error message that you get:

> This page is embedding TurboWarp in a way that is unsupported and will cease to function in the near future. Please read https://docs.turbowarp.org/embedding

**Comment by GarboMuffin** [comment]
Oh, misinterpreted what you wanted

You cannot embed the editor.

**Comment by lafkpages** [comment]
Can I embed the packager? Or should I make my own UI using the NPM package?

**Comment by GarboMuffin** [comment]
Our opinion is that if you want to "embed" the editor:

 - Open a *new tab* to our site, or
 - fork scratch-gui, or
 - figure out how to use it as a module

Using the editor in an embed will be a bad experience. Don't force your users into that.

Note that the packager does not contain the editor.

**Comment by lafkpages** [comment]
Is it possible to make a link that opens the Turbowarp editor in a new tab and load a `.sb3` file from a URL?
For example: `https://turbowarp.org/editor?file=https%3A%2F%2Fexample.com%2Fgame.sb3`

**Comment by CST1229** [comment]
> Is it possible to make a link that opens the Turbowarp editor in a new tab and load a `.sb3` file from a URL? For example: `https://turbowarp.org/editor?file=https%3A%2F%2Fexample.com%2Fgame.sb3`

https://docs.turbowarp.org/url-parameters#project_url
