### ISSUE TITLE
"Last key pressed" can't detect control key

### ISSUE THREAD

**Issue by Dieforrobux** [TurboWarp/scratch-gui#39]
### Expected Behavior
Setting the `last key pressed` thing to control

### Actual Behavior
It doesn't set `last key pressed` to control

### Steps to Reproduce
Just go to editor and click on red circle, then click on check near `last key pressed`. If that doesn't work, then it only affects chromebooks.
### Operating System and Browser

ChromeOS/Chrome Book, Version 87.0.4280.109

**Comment by GarboMuffin** [comment]
😕 
![image](https://user-images.githubusercontent.com/33787854/103934517-b7bb3200-50ea-11eb-9ac0-a5665790d105.png)

also checked on a chromebook, it works fine

**Comment by Dieforrobux** [comment]
Hmm... because on mine it reported caps AFTER i hit control

**Comment by Dieforrobux** [comment]
> Hmm... because on mine it reported caps AFTER i hit control

i tried it again didn't work

**Comment by Dieforrobux** [comment]
> 😕
> ![image](https://user-images.githubusercontent.com/33787854/103934517-b7bb3200-50ea-11eb-9ac0-a5665790d105.png)
> 
> also checked on a chromebook, it works fine

wait, what is your version ( Settings > Search > Chrome OS Version)

**Comment by Dieforrobux** [comment]
It only affects my type of chromebook for some reason, my brother tried it and it worked perfectly. 😕

**Comment by Dieforrobux** [comment]
I'm going to keep it open because someone might have the same problem

**Comment by Dieforrobux** [comment]
(brother) I guess you can't fix this. How can you fix a problem with a chromebook to a website. I probably think it isn't possible then.

**Comment by Dieforrobux** [comment]
But you can close it at any time

**Comment by Dieforrobux** [comment]
(brother) It works as the same garbomuffin does it.

![Brotherbroken](https://user-images.githubusercontent.com/71724356/103940053-c7427700-50fa-11eb-864c-d8bfa3c5a370.mhtml)

**Comment by Dieforrobux** [comment]
(brother) It works as garbomuffin does it.

![103934517-b7bb3200-50ea-11eb-9ac0-a5665790d105](https://user-images.githubusercontent.com/71724356/103940235-07a1f500-50fb-11eb-8370-e7bc3901d359.png)

I have a different mouse then garbomuffin does but it still is the same, The mouse color for mine is mine, And i do NOT use a PC mouse pluged into my chromebook, I (mostly) use the mouse on the chromebook.
