### ISSUE TITLE
Bug - Text areas

### ISSUE THREAD

**Issue by Medericoder** [TurboWarp/scratch-gui#390]
Just watch this...

https://user-images.githubusercontent.com/80577386/146680591-ca67bef0-807c-4391-b1bf-4574e6078c29.mp4

**Comment by TheColaber** [comment]
Actually, this bug is caused by the devtools addon (which means that this bug also happens with the debugger addon as well), could you create an issue in https://github.com/ScratchAddons/ScratchAddons? Turbowarp pulls its addons from there.

**Comment by GarboMuffin** [comment]
This should be fixed in the next update
