### ISSUE TITLE
dark mode in paint editor not working

### ISSUE THREAD

**Issue by SDFTDusername** [TurboWarp/scratch-gui#394]
### Expected Behavior

background in paint editor should be dark when in dark mode

### Actual Behavior

background in paint editor and buttons is still white and hurts my eyes

### Steps to Reproduce

edit something in the css files

### Operating System and Browser

Microsoft Windows 10 Home
happening in both website and desktop

**Comment by kaneryu** [comment]
you mean the canvas whre you draw? since the stage is white on start, the paint canvas should be white too?

**Comment by SDFTDusername** [comment]
its much easier for me to see when the canvas is dark

**Comment by GarboMuffin** [comment]
Next update will include a dark costume editor in dark mode
