### ISSUE TITLE
Move docs off of GH wiki

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#40]
GH wikis:

 - Cannot be translated
 - Are very limited
 - Cannot be included in desktop app to work offline
 - Poor SEO

**Comment by FunctionalMetatable** [comment]
TurboWarp Miraheze wiki 🤔

**Comment by GarboMuffin** [comment]
Instead of moving from GH wiki to another wiki platform, the plan is to move as much documentation as possible into the website itself. This has already been done for the most important wiki pages.

**Comment by GarboMuffin** [comment]
I guess https://docs.turbowarp.org/ is a thing now. That's where the wiki is moving.
