### ISSUE TITLE
Cookie Deletion, Issue or not?

### ISSUE THREAD

**Issue by kaneryu** [TurboWarp/scratch-gui#406]
**This is not reviewed by others or tested**

### Expected Behavior

You should be able to add as many extensions as you want.

### Actual Behavior

You can, but as soon as you close all Turbowarp tabs (or chrome automatically puts all of them to sleep.) all cookies are cleared

### Steps to Reproduce

Enable a lot of extensions, and make sure to customize the customizable ones. 

### Operating System and Browser
```
Google Chrome: Version 96.0.4664.111 (Official Build)  (64-bit)
Platform: 14268.67.0 (Official Build) stable-channel octopus
Channel: stable-channel
Firmware Version: Google_Fleex.11297.278.0
ARC Enabled: true
ARC: 7982014
Enterprise Enrolled: true
Developer Mode: false
```

### Visit [browsercookielimits.iain.guru](url)

**Comment by GarboMuffin** [comment]
Addon settings don't use cookies, they use localStorage, which doesn't have quite such limited storage space.

Perhaps your device is configured to clear browsing data automatically or has very little free disk space?

**Comment by kaneryu** [comment]
I've got 1.1GB available, and I don't clear automatically.
Update: Change block shape refuses to apply, I can change colors

**Comment by GarboMuffin** [comment]
Does this still happen?
