### ISSUE TITLE
Backpack

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#42]
Make the backpack work

**Comment by nova0x0** [comment]
Oh! use cookies! (The browser kind, not the food.)

**Comment by nova0x0** [comment]
or maybe LocalStorage or cloud data

**Comment by retronbv** [comment]
> Oh! use cookies! (The browser kind, not the food.)

duh 🤦🏻

**Comment by GarboMuffin** [comment]
it works since a couple days ago, forgot to close this issue
