### ISSUE TITLE
Controller settings don't save when exporting as an SB3

### ISSUE THREAD

**Issue by Starlii10** [TurboWarp/scratch-gui#420]
### Expected Behavior

Controller settings for my white Xbox One controller load in a project that has them saved.

### Actual Behavior

Controller settings do not load in a project that has them saved.

### Steps to Reproduce

1. Make a project, enable gamepad support, and customize the settings.
2. Save the project as an SB3.
3. Load the SB3 after reloading the tab.
4. The settings are gone.

### Operating System and Browser

Windows 11 Home 22000.376, Google Chrome 96.0.4664.110 (Official Build) (64-bit)

**Comment by GarboMuffin** [comment]
will be fixed in next update
