### ISSUE TITLE
Are TurboWarp Blocks open-source?

### ISSUE THREAD

**Issue by llunariis** [TurboWarp/scratch-gui#421]
Hi, I noticed that the TurboWarp blocks doesn't seem to have a URL associated with it. Does this still mean that the blocks are open-source?

**Comment by CST1229** [comment]
Like a custom extension URL? TurboWarp Blocks [is a built-in extension](https://github.com/TurboWarp/scratch-vm/tree/develop/src/extensions/tw) in TW's scratch-vm fork.

**Comment by theycallhermax** [comment]
Thank you, that answers my question!
