### ISSUE TITLE
Save custom extensions in project

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/scratch-gui#431]
Like how custom settings are stored in the file, with a note, you could do the same for extensions.
It is annoying to re open the same extensions from a link all the time. I don't think saving a link to a note is that hard neither, since there already is a system in place for it.
Thanks for your time.

**Comment by GarboMuffin** [comment]
Scratch once received a CVE for accidentally allowing this: https://github.com/advisories/GHSA-vc9j-fhvv-8vrf

Custom extensions are frankly a terrible hack and aren't something that will be seeing any significant improvements any time soon.

**Comment by TheShovel** [comment]
> Scratch once received a CVE for accidentally allowing this: [GHSA-vc9j-fhvv-8vrf](https://github.com/advisories/GHSA-vc9j-fhvv-8vrf)
> 
> Custom extensions are frankly a terrible hack and aren't something that will be seeing any significant improvements any time soon.

understandable
