### ISSUE TITLE
Credits page

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#46]
Make a credits page to thank everyone who makes this project possible at all

 - fosshost
 - translators
 - addon people
 - ???

**Comment by retronbv** [comment]
Do I get counted as an addon person?

**Comment by GarboMuffin** [comment]
"Addon people" would be anyone with their name in an addon's `credits: ` and maybe translators

**Comment by GarboMuffin** [comment]
Here's the new credits page: https://staging.turbowarp.org/credits.html

Tentative design still. Link from homepage will be added soon
