### ISSUE TITLE
Project lags when any variable changes

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/scratch-gui#462]
Seems like the project lags when any variable changes. For example, when in my game I take damage, the variable "P1 Health" changes so the game start lagging until the variable hasn't stopped changing.

**Comment by GarboMuffin** [comment]
To be clear, you're talking about the on-screen variable watchers that appear over the project player AND you're referring to projects generated by the packager?

**Comment by Alestore** [comment]
Yes, but the project is INSIDE TurboWarp. After packaging the project doesn't lag.
If you want a video of it or you want to test yourself, I can send you the file of the project via mail.

**Comment by GarboMuffin** [comment]
For now, the lag should be fixed if you disable the "Hide new variables" addon until the next update is released this weekend. If that doesn't fix it, let me know
