### ISSUE TITLE
Hiding mouse/custom cursors

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#48]
> can you add a feature in turbowarp which makes the user's mouse hidden inside the project window

**Comment by InfinityGamesStudios** [comment]
**Yes or no.** For hiding the mouse Chrome should say *"Press [ ESC ] to show the cursor"*. For a custom cursor, I think that the custom cursor should be a TurboWarp costume, true? Or maybe other. And if it is really a costume, TurboWarp should warn the user that he/she can't make an empty costume for a cursor. So... maybe.

**Comment by CST1229** [comment]
Resolved by the Mouse Cursor extension.
