### ISSUE TITLE
Dark mode embeds

### ISSUE THREAD

**Issue by Dhuls-Scratch** [TurboWarp/scratch-gui#481]
### Expected Behavior

_Please describe what should happen_

Embeds should be dark mode to match a website dark theme, or there should be an option

### Actual Behavior

_Describe what actually happens_

There isn't

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

Windows 10 Edge 99

This could also solve ScratchAddons/ScratchAddons#4430

**Comment by mxmou** [comment]
> This could also solve [ScratchAddons/ScratchAddons#4430](https://github.com/ScratchAddons/ScratchAddons/issues/4430)

Only if it accepts a custom background color.

**Comment by Chiroyce1** [comment]
Maybe a URL parameter can be used for the custom colour (so that it works with SA) ... and if the parameter isn't given, default to white (so that it works normally as well).

**Comment by retronbv** [comment]
> Maybe a URL parameter can be used for the custom colour (so that it works with SA) ... and if the parameter isn't given, default to white (so that it works normally as well).

IMO the fallback hierarchy should be `URL parameter > TW dark/light preference > system D/L preference > white`

**Comment by GarboMuffin** [comment]
TurboWarp embeds have respected the system's dark mode preference in fullscreen for some time now and there is a URL parameter to override this https://docs.turbowarp.org/embedding#fullscreen-background
