### ISSUE TITLE
Add "last key pressed" as vanilla Scratch block

### ISSUE THREAD

**Issue by qucchia** [TurboWarp/scratch-gui#482]
When the "last key pressed" block from the TurboWarp Blocks extension is inside a project it cannot be uploaded to Scratch. However, the vanilla custom block reporter with the name "last key pressed" functions the same way and _can_ be uploaded to Scratch (similar to the "is compiled?" and "is TurboWarp?" blocks). I suggest this block be added to the block toolbox in the extension, like so:

![image](https://user-images.githubusercontent.com/45072410/159537166-a9e8ff45-e595-48ea-b22c-fada56e32e75.png)

It's as simple as [adding a line to `make-toolbox-xml.js`](https://github.com/qucchia/scratch-gui/commit/fc3e54d369e960ed1e3e521ceff9627c8a21e350). I can make a pull request of this if it's approved.

**Comment by GarboMuffin** [comment]
This is currently intentional

**Comment by GarboMuffin** [comment]
See previous comment
