### ISSUE TITLE
Variable value glitch/bug on the TurboWarp editor

### ISSUE THREAD

**Issue by aquaslvt** [TurboWarp/scratch-gui#50]
I found a bug/glitch on TurboWarp (with an addon enabled), I will put a video here so we can see. (This is a common glitch/bug for any website or software.)

https://user-images.githubusercontent.com/68143381/105862233-d9278380-5fef-11eb-9c7b-f4ccc633901b.mp4

**Comment by TheColaber** [comment]
This bug has been fixed in the ScratchAddons/ScratchAddons master branch. This issue will be fixed when GarboMuffin pulls again.
