### ISSUE TITLE
New Logo?

### ISSUE THREAD

**Issue by AnnoyedArt1256** [TurboWarp/scratch-gui#51]
I made a logo for Turbowarp in SVE. Here's the logo

![turbowarp logo](https://user-images.githubusercontent.com/66080161/106167458-4547ea00-619e-11eb-8532-42f563778bdd.png)

here's the original .svg file https://drive.google.com/file/d/1BDPmE11N_ApXn5A85FJnnSiXC76yvYDB/view?usp=sharing

It's of course based on the Javascript logo. Hope you like it!

**Comment by GarboMuffin** [comment]
The next version of TW will have a proper favicon
