### ISSUE TITLE
Interpolation has a typo, "Interplotation".

### ISSUE THREAD

**Issue by zaqzar447** [TurboWarp/scratch-gui#515]
### Expected Behavior

_It should say Interpolation_

### Actual Behavior

_It says Interplotation instead_
![interplotatiohn](https://user-images.githubusercontent.com/83273963/168415029-850f3a98-1c6e-4c67-806c-fe955f210fa0.png)

**Comment by zaqzar447** [comment]
Would probably take less than a minute to fix

**Comment by CST1229** [comment]
It's fine for me, it's your browser translator doing something.
![kép](https://user-images.githubusercontent.com/68464103/168416836-4051ad77-a99f-4cb1-9e16-7f5c8be97eca.png)

**Comment by GarboMuffin** [comment]
It looks like you're language is set to Swedish. The TurboWarp translations into Swedish appear to be very incomplete and apparently not high quality. I've manually modified a couple translations to fix this issue in the next update, but if you want to see a proper Swedish translation, you're welcome to help fix it: https://docs.turbowarp.org/translate
