### ISSUE TITLE
Blocks disappeared in the editor!

### ISSUE THREAD

**Issue by MODmasterBlock** [TurboWarp/scratch-gui#525]
### Expected Behavior

The blocks were supposed to be displayed in the blocks palette

### Actual Behavior

There were no blocks in the palette

### Steps to Reproduce

You have to estimate which block is where (example, if i want to drag create clone of myself block, I need to know the exect location of it)

### Operating System and Browser

Windows 11 home edition Chrome Browser 101.0.4951.67

### Secreenshot

<img width="960" alt="Screenshot 2022-05-25 164926" src="https://user-images.githubusercontent.com/105857005/170250609-5b5f7ad7-acea-4e6f-84dd-e65ff3dfa2be.png">

**Comment by GarboMuffin** [comment]
Does this still happen?

**Comment by GarboMuffin** [comment]
If this still happens, please comment
