### ISSUE TITLE
Could not load project: SyntaxError: Unexpected token in JSON at position 0

### ISSUE THREAD

**Issue by pringlepyoru** [TurboWarp/scratch-gui#529]
I'm unable to show the symbol that appears as it wont let me paste it, however I have uploaded a screenshot below. I reset my PC recently however the .sb3 file was on a separate drive and disconnected during the reset so I don't know how I'm unable to load my project, that's the only logical reason I can think of; any help would be appreciated, thanks :)

![image](https://user-images.githubusercontent.com/86434713/170822313-2ddceee9-e70a-4115-a428-44b6778e5ece.png)

**Comment by GarboMuffin** [comment]
please email the project file to contact@turbowarp.org or post it here publicly

**Comment by GarboMuffin** [comment]
see email
