### ISSUE TITLE
Broken broadcasts and clone names in debugger addon

### ISSUE THREAD

**Issue by ghost** [TurboWarp/scratch-gui#537]
### Expected Behavior
When a **broadcast (message)** block is run in a project, a log will be added to the debugger displaying "_broadcasted_" followed by the name of the message broadcasted and clones created with the **create clone of (sprite)** are logged as "Created clone of" and the name of the parent sprite. Any clones of sprites listed on the right side of the debugger will show as "Clone of (sprite name)".

### Actual Behavior
Logged broadcasts and clone creations show the **{broadcast}** or **{sprite}** variable name instead of their actual value. Some clones in the sprite list on the right also appear as "unknown sprite".
![image](https://user-images.githubusercontent.com/75924474/173163470-13ca8f7a-274c-4ceb-823f-461b69b79d9f.png)

### Steps to Reproduce
Enable the "Debugger" addon in the TurboWarp web editor or Desktop app and check the "Log Broadcasts" and "Log Clone Creations" checkboxes, then run a project containing clones and broadcast blocks. (_[this project](https://turbowarp.org/399048563/editor) used in the picture above is a good example_)

### Operating System and Browser
Debian Linux 11 bullseye, TurboWarp Desktop v1.3.0

**Comment by GarboMuffin** [comment]
It seems like the {broadcast} and {sprite} issue is already fixed in the latest development version (no idea what happened there)

I will fix (unknown sprite) and some other issues related to clones in the next update too
