### ISSUE TITLE
Create our own version of the Scratch Cat

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#54]
You know how every new Scratch project has the Scratch Cat? We need something like that to replace our empty sprite.

It doesn't even need to be an animal (see [Snap!](https://snap.berkeley.edu/snap/snap.html))

It could just be something from Scratch's builtin sprite library

**Comment by FunctionalMetatable** [comment]
Use Amon xD

**Comment by FunctionalMetatable** [comment]
Jokes aside, I think TurboWarp would need a custom one, or a Panther because TurboWarp is really fast.

**Comment by easrng** [comment]
<img src="https://owo.whats-th.is/75xG5hH.svg" alt="A vector image of a sitting cat hat is red and has a large head." width="256px">

How's this? It's a modified version of one of the old noto emojis (from Android 8).

**Comment by retronbv** [comment]
> _-snip-_

I like this image

**Comment by GarboMuffin** [comment]
@easrng 

 - do you know what the licensing on the original file is?
 - change the reds to be closer to #ff4c4c, that's the color TW uses for everything
 - make it face the other way

Otherwise this is fine

**Comment by GarboMuffin** [comment]
It seems like this SVG causes issues when imported into Scratch, that's something that needs to get fixed (probably by changing the SVG?)

(You shouldn't worry about this, I'll look into it when I decide on something)

**Comment by GarboMuffin** [comment]
Another one to consider: https://scratch.mit.edu/projects/488598907/editor/

**Comment by Riptide-Scratch** [comment]
> It seems like this SVG causes issues when imported into Scratch, that's something that needs to get fixed (probably by changing the SVG?)

Actually svg's are already broken when you upload to scratch. It's a bug on the scratch side.

**Comment by Riptide-Scratch** [comment]
And this perhaps? It was created in google drawings by stacking multiple letters with the font Faster One.
![Turbowarp icon (1)](https://user-images.githubusercontent.com/70417080/108886498-e23f4c80-75bd-11eb-96a3-8bfb03ed65e4.png)

**Comment by FunctionalMetatable** [comment]
> 
> How's this? It's a modified version of one of the old noto emojis (from Android 8).
> 
I like this

**Comment by easrng** [comment]
> * do you know what the licensing on the original file is?

Apache 2.0, should be compatible with BSD or GPL or whatever.

> * change the reds to be closer to #ff4c4c, that's the color TW uses for everything

I used the red from the editor bar.


> * make it face the other way

Can do

**Comment by thiyageshvenkat** [comment]
I like the idea of creating a scratch-related icon.

**Comment by GarboMuffin** [comment]
The dango is here to stay 🍡

**Comment by Chaos-emerald** [comment]
See #134

**Comment by ghost** [comment]
> The dango is here to stay 🍡

but, what is a dango, why

**Comment by retronbv** [comment]
A dango is a god-like being that must be praised

**Comment by Chaos-emerald** [comment]
> > The dango is here to stay 🍡
> 
> but, what is a dango, why

A dango is a food.

**Comment by Chaos-emerald** [comment]
> A dango is a god-like being that must be praised

No, it's a food.
