### ISSUE TITLE
Cloud variable limit changes

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#545]
- Make cloud variables unlimited again
 - Display a warning when creating more than 10 cloud variables as it won't load properly in Scratch

**Comment by TimMcCool** [comment]
This opens many new possibilities 🥳

**Comment by GarboMuffin** [comment]
To be clear, this refers to number of variables (not length) and really only helps things like the packager.

If you upload the project to scratch, any variables beyond 10 will be converted to not cloud variables.

**Comment by TimMcCool** [comment]
I believe this can be circumvented by sending a modified project json (with more than 10 cloud variables) directly to the API endpoint
