### ISSUE TITLE
TurboWarp should have a logo in the editor

### ISSUE THREAD

**Issue by superscratch444tre** [TurboWarp/scratch-gui#56]
TurboWarp should have a logo in the editor, like scratch has:

<img width="218" alt="Scratch" src="https://user-images.githubusercontent.com/69812464/108315965-1aa4ec00-71b4-11eb-968f-54cdf44a0cff.png">

I think is should look like this (I just inserted the picture to the scratch website, it's just an example):

<img width="342" alt="tw example" src="https://user-images.githubusercontent.com/69812464/108316084-4aec8a80-71b4-11eb-9c09-10b04cb430f1.png">

Files:

svg:   https://superscratch444tre.000webhostapp.com/turbowarp.svg

png:   ![turbowarp](https://user-images.githubusercontent.com/69812464/108316209-80917380-71b4-11eb-922c-18e38c35de6f.png)

Edit:    https://superscratch444tre.000webhostapp.com/new-turbowarp.svg
           
![edit](https://user-images.githubusercontent.com/69812464/108362824-1eecfb80-71ec-11eb-9a32-086449fb7762.png)

Outline:

![outline](https://user-images.githubusercontent.com/69812464/108474711-a63b7d00-7287-11eb-9d66-892c84475bc0.png)

svg:   https://superscratch444tre.000webhostapp.com/outline.svg

**Comment by GarboMuffin** [comment]
I think it's fine as-is. There's very little space left in the menu bar anyways right now.
