### ISSUE TITLE
A way to change the resolution

### ISSUE THREAD

**Issue by adazem009** [TurboWarp/scratch-gui#57]
[HTMLifier](https://sheeptester.github.io/htmlifier/) has a feature, which can be used to change the output project resolution. For example, I can choose 1920x1080, so the project fills my screen.
Some of my projects require high performance, so I use TurboWarp for them. It'd be great if there was a way to change the resolution as HTMLifier doesn't offer the performance TurboWarp has.

**Comment by retronbv** [comment]
I don’t know if you already know this, but turbowarp has a HTMLifier. I don’t think it currently has this feature... but it might soon

**Comment by GarboMuffin** [comment]
This is possible on the website: https://turbowarp.org/?size=640x360

For packager options, follow https://github.com/TurboWarp/packager/issues/19
