### ISSUE TITLE
color picker popover shown in the wrong layer

### ISSUE THREAD

**Issue by waterblock79** [TurboWarp/scratch-gui#574]
### Actual Behavior

![image](https://user-images.githubusercontent.com/33573572/180947354-d0a1476a-d96c-401e-a4ff-2a9242bd3d08.png)

Color picker shown in the wrong layer, and it caused the button which used to change filling mode was covered by the navbar.

### Steps to Reproduce

Adjust the page zoom to 100% or bigger, open 'costumes' and open the popover which used to set the filling, then set the filling mode to gradient.

### Operating System and Browser

Windows 11 22H2, Chrome 103.0.5060.134.

**Comment by GarboMuffin** [comment]
should be fixed in the next update

**Comment by GarboMuffin** [comment]
See if this is fixed in the development version: https://staging.turbowarp.org/editor

**Comment by waterblock79** [comment]
> See if this is fixed in the development version: https://staging.turbowarp.org/editor

it shows in the right layer now, thanks :)
