### ISSUE TITLE
Bug: Changing language with a custom extension will duplicate it

### ISSUE THREAD

**Issue by Mickmick21** [TurboWarp/scratch-gui#593]
image:
<img width="293" alt="Capture d’écran 2022-08-15 à 20 33 51" src="https://user-images.githubusercontent.com/110345721/184694733-15a8e773-6ddb-43b8-bf9d-c1b0f9c8a0b7.png">
this is not disturbing (for me)

**Comment by GarboMuffin** [comment]
Duplicate of https://github.com/TurboWarp/scratch-gui/issues/593

**Comment by cobaltt7** [comment]
This is #593

**Comment by GarboMuffin** [comment]
Oops

Duplicate of https://github.com/TurboWarp/scratch-gui/issues/637
