### ISSUE TITLE
monospaced fonts

### ISSUE THREAD

**Issue by superbeelavaman** [TurboWarp/scratch-gui#6]
## please add this feature! ##
There should be a button to set lists and variables to a monospaced font so that users can view and create lists look better.

current methods:
 hard | easy (need to add)
------------ | -------------
go into browser settings | advanced button
change primary font | new monospaced font toggle

- [x] hard way (on most browsers)
- [ ] easy way (add this)

**Comment by GarboMuffin** [comment]
What projects would this be useful for?

If you want something between "hard" and "easy", open the browser console and run:

```js
const style = document.createElement('style');
style.innerText = '* { font-family: monospace !important; }';
document.head.append(style)
```

**Comment by superbeelavaman** [comment]
ok that makes sense.

**Comment by GarboMuffin** [comment]
I don't see why this would be necessary, so I'm not going to add it.
