### ISSUE TITLE
The plan with custom extensions

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#633]
Checkboxes mean "the code has been written", not necessarily "you can use it now"

- [x] Store custom extension URLs in the project
- [x] Add confirmation for loading non-extensions.turbowarp.org extensions
- [x] Automatically load extensions (with user consent)
- [x] In the packager, parse customExtensions and inform the user ahead of time
- [x] Implement an unsandboxed extension mode
- [ ] Figure out the local development and debugging situation
- [ ] Remove the temporary development support hack (localhost:8000)
- [x] make global.Scratch actually unique per extension
- [x] Use unsandboxed extensions in the packager because the Worker sandbox sucks and the iframe sandbox doesn't work https://github.com/TurboWarp/packager/issues/550
- [x] Add APIs like Scratch.vm
- [x] Convert extensions on extensions.turbowarp.org to IIFE
- [x] Allow extensions from extensions.turbowarp.org to run unsandboxed
- [x] Add Box2D to extensions.turbowarp.org (like https://github.com/TurboWarp/scratch-gui/discussions/632)
- [x] Add Utilities to extensions.turbowarp.org
- [x] Add gamepad extension to extensions.turbowarp.org
- [x] Add file reading extension to extensions.turbowarp.org https://github.com/TurboWarp/extensions/pull/19
- [x] Add pointer lock extension to extensions.turbowarp.org https://github.com/TurboWarp/extensions/pull/18
- [x] Figure out the deal with non-edge-activated hats: `isEdgeActivated: false`
- [x] Open submissions to extensions.turbowarp.org with some guidelines
- [x] Advertise extensions.turbowarp.org in the editor
- [x] Make extensions.turbowarp.org a bit less ugly
- [x] Figure out how to make this work offline with the desktop app
- [x] Document the correct way to do casting
- [x] ScratchX

**Comment by David-Orangemoon** [comment]
Awesome. Glad to see unsandboxed extensions getting full support! Plan to add any community ones to the extension list?

**Comment by GarboMuffin** [comment]
The plan is to restrict unsandboxed extensions to extensions.turbowarp.org (no change for current sandboxed extensions), but allow community contributions to that website as long as they follow guidelines like "don't break compatibility with old extension versions" and "don't introduce security bugs"

**Comment by GarboMuffin** [comment]
https://twitter.com/GarboMuffin/status/1584025942376448001

The hope is that users will be able to start using this in ~1wk

**Comment by GarboMuffin** [comment]
Prototypes can be tested now:

 - https://experiments.turbowarp.org/unsandboxed-extensions/
 - https://extensions.turbowarp.org/

Extension URLs will be stored in the project. Extensions from https://extensions.turbowarp.org/ will be loaded automatically and unsandboxed. For extensions from other places, a prompt will be displayed and they will be loaded with the sandbox. The prompt is rather ugly and needs some more work.

It's not clear what the final solution will be for locally testing unsandboxed extensions. For now, I've made it so extensions with a URL beginning with `http://localhost:8000/` exactly will be loaded as unsandboxed. This is temporary for testing purposes.

extensions.turbowarp.org can probably start accepting contributions over here: https://github.com/TurboWarp/extensions. The acceptance criteria is basically something like "nothing malicious, no security bugs, don't break compatibility".

**Comment by GarboMuffin** [comment]
Also, there is some draft documentation here: https://docs.turbowarp.org/development/unsandboxed-extensions

**Comment by TheShovel** [comment]
The prompt doesn't appear for my extension, even tho it uses the vm.

**Comment by fractioneater** [comment]
I wasn't sure whether to open an issue for this or put it here, but in the Utilities extension, the label in the block palette is "Utlities" (without the first i).

**Comment by matmanna** [comment]
I might be able to work on the https://extensions.turbowarp.org site CSS/layouts or make some improvements in order to increase consistency with other Turbowarp tools. 👍 

**Also, could the item "Advertise extensions.turbowarp.org in the editor" be solved by adding an option under the Edit > menu in the Turbowarp editor called "Unsandboxed Extensions" that opens the https://extensions.turbowarp.org site?**

**Comment by GarboMuffin** [comment]
Feel free to take a shot at redesigning extensions.turbowarp.org. You can't do worse than the current design.

As for advertising these in the editor, I was intending to add an item alongside the custom extension button that says something about visiting that website to find some more extensions. Something like that.

**Comment by GarboMuffin** [comment]
Unsandboxed extensions are now usable on the normal turbowarp.org without any experiment branches
