### ISSUE TITLE
Addons 1.29

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#638]
- [x] block-palette-icons: icons are looking strange
 - [x] color-picker: scratchAddons.opacitySliderAlpha
 - [x] editor-theme3, editor-devtools, find-bar, debugger: test if TurboWarp blocks and other extensions appear right
 - [x] editor-theme3: customCssVariables
 - [x] editor-theme3: setCustomBlockColor needs to update the bubble's color, or we replace the bubble with an icon
 - [x] editor-devtools, find-bar: remove devtools extension check
 - [x] mute-project: hide-icon.css if vol-slider enabled
 - [x] update `#s3devToolBar` selector in shared spaces implementation
 - [x] https://github.com/TurboWarp/scratch-gui/issues/630
 - [x] https://github.com/ScratchAddons/ScratchAddons/pull/5403
 - [x] https://github.com/ScratchAddons/ScratchAddons/pull/5405
 - [x] `git merge tw-1.29` in TW/addons
 - [x] merge VM parts
 - [x] find-bar dark mode
 - [x] middle click popup
 - [x] volume-slider hiding

**Comment by WorldLanguages** [comment]
bump? should this be closed or updated?

**Comment by GarboMuffin** [comment]
the issue remains up-to-date, unfortunately

**Comment by WorldLanguages** [comment]
whoops - I wrongly assumed the referenced PRs were yours

**Comment by GarboMuffin** [comment]
This is a todo list of things necessary to make 1.29 work aside from just `git pull upstream master`. You will probably not see any of these go upstream because they're TW specific

**Comment by WorldLanguages** [comment]
@GarboMuffin Okay. Keep in mind SA is always open to make changes that make it easier to integrate it into Scratch editor forks, as long as they don't overcomplicate running the addons as part of a browser extension.

**Comment by GarboMuffin** [comment]
I actually just forgot about this issue for about 3 weeks. Making quite a bit of progress now. There will be some PRs trickling upstream over the next bit.
