### ISSUE TITLE
Turn off Cloud variables on projects that use the camera

### ISSUE THREAD

**Issue by DNin01** [TurboWarp/scratch-gui#654]
There have been an increasing number of creations that use the Video Sensing extension to take pictures and then upload them to Cloud variables. This is obviously personal information disclosure. Scratch just received a feature that turns off Cloud variables when Video Sensing blocks are being used: https://github.com/LLK/scratch-www/pull/7165 🎉

But I'm not sure if this is still possible in TurboWarp, and if it is, it would be nice if Cloud variables were automatically disabled when Video Sensing blocks are detected.

**Comment by GarboMuffin** [comment]
We have resolved this in a different way: If the project contains cloud variables or custom extensions, sensing the color of the webcam should be disabled.

The rationale for not following Scratch was that disabling custom extensions (which we have to assume let people exfiltrate data) while video sensing is enabled wouldn't make sense, and the end result is the same: don't combine cloud variables and video sensing.

**Comment by GarboMuffin** [comment]
If you can find a way to sense webcam color while cloud variables or custom extensions are in use, please let me know: security@turbowarp.org
