### ISSUE TITLE
More area or extent of zoom-out for costume/backdrops editing is needed when stage is big

### ISSUE THREAD

**Issue by snownstone** [TurboWarp/scratch-gui#67]
Thank you for your work and sharing!

Custom setting of stage size is really nice. But when the size of stage is  as big as 1920*1080, area left for costume/backdrop editing is limited and no way to see the editing boundary, even displaying the stage in a small window. More area or extent of zoom-out for editing is needed.

**Comment by GarboMuffin** [comment]
Consider using a smaller stage with the aspect ratio you want (say, 640x360) and use fullscreen to make it larger

**Comment by snownstone** [comment]
> Consider using a smaller stage with the aspect ratio you want (say, 640x360) and use fullscreen to make it larger

Yeah, it works perfectly. Thank you.
