### ISSUE TITLE
Scratch GUI gives errors when Scratch Blocks is linked

### ISSUE THREAD

**Issue by Erts57** [TurboWarp/scratch-gui#678]
### Expected Behavior

I followed the instructions on the [TurboWarp documentation](https://docs.turbowarp.org/development/getting-started) with building the scratch-gui along with scratch-render, scratch-vm and I included the scratch-blocks. Hopefully it would compile and work  this time. I would try to fix it myself but I really don't understand what the error is.

### Actual Behavior

Everytime I add scratch-blocks it doesn't work. I have tried this without scratch-blocks and only with scratch-render, scratch-vm, and scratch-gui and it works perfectly fine. When I mess around with the `blockly_compressed_verticle.js` file it reports a new error saying Blockly is not defined.

![Screenshot 2022-12-30 094033](https://user-images.githubusercontent.com/73663747/210094035-4f439a3c-da37-4508-b04f-212e8501be1d.png)

![Screenshot 2022-12-30 094053](https://user-images.githubusercontent.com/73663747/210093309-d363b13b-3a37-4ea7-8fc2-7b16c2a20e31.png)

### Steps to Reproduce

```
git clone https://github.com/TurboWarp/scratch-gui scratch-gui
cd scratch-gui
npm ci
npm start
^C
cd ..
git clone https://github.com/TurboWarp/scratch-blocks scratch-blocks
git clone https://github.com/TurboWarp/scratch-vm scratch-vm
git clone https://github.com/TurboWarp/scratch-render scratch-vm
cd scratch-vm
npm ci
npm link
cd ../scratch-render
npm ci
npm link
cd ../scratch-blocks
npm ci
npm link
cd ../scratch-gui
npm link scratch-blocks scratch-render scratch-vm
npm start
```

### Operating System and Browser

Windows 11, Google Chrome

**Comment by GarboMuffin** [comment]
scratch-blocks requires a manual build step

```
npm run prepublish
```

Note that:

 - This requires Python 2
 - You must restart the scratch-gui server each time you build scratch-blocks
 - I have never successfully run a build on a Windows computer
 - Consider looking into "WSL"

Good luck

**Comment by CST1229** [comment]
> - I have never successfully run a build on a Windows computer

I have built scratch-blocks on Windows on at least one occasion by applying [this PR](https://github.com/LLK/scratch-blocks/pull/2138)'s changes.

**Comment by GarboMuffin** [comment]
I will look into adding more documentation to scratch-blocks' README and see if that PR still applies (probably does)

**Comment by Erts57** [comment]
Thanks so much, I applied the changes from [this](https://github.com/LLK/scratch-blocks/pull/2138) and now it works :D
