### ISSUE TITLE
Improve the custom extension URL input

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#679]
A certain "Plugin Loader UI" by Lukas Studio TV adds a menu that looks like this:

![image](https://user-images.githubusercontent.com/33787854/210108422-c194d0e6-d8ba-4700-a324-b83141fee3f5.png)

This seems like a good starting place:

 - Doesn't use prompt()
 - URL input still there
 - Option to paste extension code exists
 - We probably won't do presets?

**Comment by David-Orangemoon** [comment]
Yeah I like that menu too. I think it would be beneficial for custom extensions to thrive.
