### ISSUE TITLE
Color removed from some popups

### ISSUE THREAD

**Issue by fractioneater** [TurboWarp/scratch-gui#680]
### Expected Behavior

The blocks listed in the find bar and middle click popup should be colored the same as their block would be colored.
This was happening until a recent commit.

### Actual Behavior

The find bar shows dark gray text on a black background, and the middle click popup doesn't show color unless the item is selected.

<details>
<summary>Images that take up more space than they should</summary>

![tw-colorless-popup](https://user-images.githubusercontent.com/98233032/210154084-33294270-d5f6-435e-902c-f9e1573f4bb7.png)

![tw-colorless-findbar](https://user-images.githubusercontent.com/98233032/210154085-29215513-496b-4c7b-b919-4ae5493ee493.png)
</details>

### Steps to Reproduce

Set the block color to either "Colored on white background" or "Colored on black background."
Go to the editor of a project that has code in it.
Make sure the find bar and block creator popups are enabled
Click ctrl+f, and then open the "add block by name" popup.
Observe the absence of color.

### Operating System and Browser

ChromeOS 108

**Comment by GarboMuffin** [comment]
I believe two issues are occurring:

 - TW bug regarding addon CSS causes find bar colors to be wrong sometimes, should be fixed after reload. If that's not the case, there's another bug here I am not aware of.
 - SA bug regarding middle click popup not supporting custom colors properly. Will be fixing it.

**Comment by fractioneater** [comment]
> TW bug regarding addon CSS causes find bar colors to be wrong sometimes, should be fixed after reload.

The find bar colors are correct after reloading.

**Comment by GarboMuffin** [comment]
This should be fixed now -- please check

I'll keep this issue open for now because I "fixed" the find-bar bug by requiring a reload for certain block color settings to apply, which is not a permanent solution

**Comment by fractioneater** [comment]
No, it still isn't fixed until I reload.

**Comment by fractioneater** [comment]
Also, the middle click popup looks worse than it did before:

![image](https://user-images.githubusercontent.com/98233032/210182712-1f44cea3-2e5a-40ae-93cf-e0bacec87e98.png)

**Comment by GarboMuffin** [comment]
This should be actually fixed on https://staging.turbowarp.org/editor now

(It's too late in the day for me to be comfortable deploying this to production)
