### ISSUE TITLE
Comment text color is black on dark gray

### ISSUE THREAD

**Issue by fractioneater** [TurboWarp/scratch-gui#685]
### Expected Behavior

Comments should have white text if the block colors are set to "colored on black background".

### Actual Behavior

I'm assuming this is another upstream issue that only affects TurboWarp.
![image](https://user-images.githubusercontent.com/98233032/210649306-7a709367-6ac4-4a5f-a21b-2bf71ed7a963.png)

### Steps to Reproduce

Set the block colors to "Colored on black background"
Make a comment, and type in it

### Operating System and Browser

ChromeOS 108

**Comment by GarboMuffin** [comment]
I can't reproduce this

<img width="276" alt="image" src="https://user-images.githubusercontent.com/33787854/210651770-d16808c8-414a-46c4-baae-4d3816cd5aae.png">

**Comment by fractioneater** [comment]
I can reproduce it with only `editor-theme3` enabled. If I switch to light theme and then back, it's fixed. Also, the exact same thing happens with the searchable dropdown text input.

**Comment by GarboMuffin** [comment]
Found the issue, will get this fixed
