### ISSUE TITLE
Incorectly spelled addon (in French)

### ISSUE THREAD

**Issue by Mickmick21** [TurboWarp/scratch-gui#688]
### Expected Behavior

The Addon Should spell "quand"

### Actual Behavior

The Addon actualy spells "quuan" (like if you say whee)
 
![Capture d’écran 2023-01-06 175722](https://user-images.githubusercontent.com/110345721/211060955-922d9cd6-945b-44fd-8a7c-71bc4ebef0b1.png)

### Steps to Reproduce

Search for "Menus Déroulant colorés" in the addons (In French)

### Operating System and Browser

Does not matter

**Comment by WorldLanguages** [comment]
Fixed on Transifex

New addon description is:
> Menus contextuels colorés quand on fait un clic droit sur un bloc.

**Comment by Mickmick21** [comment]
thanks, now its spelled correctly

**Comment by Mickmick21** [comment]
![image](https://user-images.githubusercontent.com/110345721/215257888-24a90172-afe0-4699-9f90-f2474fbcdd7e.png)
