### ISSUE TITLE
[FEATURE REQUEST] New Block Colors

### ISSUE THREAD

**Issue by guest123guest** [TurboWarp/scratch-gui#691]
There's a test for higher contrast block colors on the Scratch Lab: https://lab.scratch.mit.edu/contrast-blocks/
I wouldn't mind having these colors as an optional TurboWarp add-on, though you might leave in the old colors by default.

I'm not sure if this belongs here or in scratch-gui, so please tell me if this is the right repository or not.

**Comment by DNin01** [comment]
I think all blocks in TurboWarp and its custom extensions should be updated to fit the new palette. Users can always use one of the addons to go back to the old colors if they want to.

**Comment by GarboMuffin** [comment]
We will get the new colors when Scratch does

**Comment by EJD799** [comment]
Just make it a preset for the custom block colors addon.

**Comment by DNin01** [comment]
> Just make it a preset for the custom block colors addon.

What about the custom extensions?

**Comment by Mickmick21** [comment]
It's here 
![image](https://github.com/TurboWarp/scratch-gui/assets/110345721/8df35f63-2041-4af5-81f8-4b8132b3923c)

**Comment by GarboMuffin** [comment]
:tada: high contrast mode and a lot of other things have just been merged :tada:
