### ISSUE TITLE
URL parameters to control addons

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#70]

**Comment by retronbv** [comment]
Would the url parameters include the settings for the addons? This could result in some very long urls.

**Comment by GarboMuffin** [comment]
yes, they would be very long

**Comment by retronbv** [comment]
> yes, they would be very long

maybe it could link to a json file on the web, the file could be like the export/import settings for sa

**Comment by Chaos-emerald** [comment]
Can cause long boi urls

**Comment by Emerald-chaos** [comment]
Why did you block me for saying
> Can cause long boi urls

?

**Comment by GarboMuffin** [comment]
I marked "Can cause long boi urls" as off-topic because the point it is making has already been noticed and acknowledged and I felt that it did not add anything to the discussion.

You have been blocked on several occasions for spamming this issue tracker with various things. The comment you have just made is an example of one of these comments. Please, I want my GitHub notifications to *mean something*. Those comments don't help.

**Comment by GarboMuffin** [comment]
Will reconsider if anyone has a specific URL parameter format proposal and a specific use case in mind

**Comment by retronbv** [comment]
Personally i would link to a file on the web (JSON, etc.) `?url=https://myaddonsettings.com/settings.json`

**Comment by GarboMuffin** [comment]
The settings would have to be encoded in the URL. Fetching a file is not a good solution (due to CORS and async nature of requests)

**Comment by GarboMuffin** [comment]
A new parameter is being added:

?addons=pause,mute-project,remove-curved-stage-border

Comma separated list of addons to run. If specified, will disable all default addons and ignore local settings. Settings not supported but not super important anyways for intended use case. Will work in embed.

**Comment by GarboMuffin** [comment]
Intended for embed but can be used on any page

https://docs.turbowarp.org/embedding#addons

https://turbowarp.org/15832807/embed?addons=pause,gamepad,mute-project
