### ISSUE TITLE
fetaure : convert mono to stereo sounds

### ISSUE THREAD

**Issue by Mickmick21** [TurboWarp/scratch-gui#701]
here is how a wav header works
<img width="717" alt="Capture d’écran 2023-01-13 à 13 07 10" src="https://user-images.githubusercontent.com/110345721/212316905-a29cec26-3506-4813-a83f-be868680ac56.png">
it should be easy ? (Right ?????)

**Comment by CST1229** [comment]
You can't get stereo data back from a single-channel sound, that's just not how it works.
