### ISSUE TITLE
Show what extensions are being used on the project page

### ISSUE THREAD

**Issue by DNin01** [TurboWarp/scratch-gui#711]
I'm sometimes interested, for privacy reasons, what [custom extensions](https://extensions.turbowarp.org/) a project might be using. If you use an extension in a project on the Scratch website, it'll put badges for each extension under the project player on the project page. Could we do something similar for TurboWarp? It'd be especially useful since it can disclose whether the project may make web requests and stuff like that.

**Comment by GarboMuffin** [comment]
I think just listing the extensions won't help a whole lot (knowing a project uses "fetch" is awfully vague); rather we will require permission from the user before doing certain things:

 - loading extensions from places other than extensions.turbowarp.org requires explicit permission
 - extensions on extensions.turbowarp.org will very soon require explicit permission before making network requests to any website other than GitHub and maybe a small selection of other sites
