### ISSUE TITLE
Turbowarp prompts the user to allow Gitlab

### ISSUE THREAD

**Issue by Mickmick21** [TurboWarp/scratch-gui#717]
### Expected Behavior

Gitlab should be allowed on Turbowarp

### Actual Behavior

Even if it's in the list, it still prompts the user to alow the website

### Steps to Reproduce

use fetch to fetch anything from Gitlab

**Comment by GarboMuffin** [comment]
What GitLab URL are you trying to fetch?

**Comment by Mickmick21** [comment]
https://gitlab.com/api/v4/projects/Mickmick2012%2FLibreOS/repository/files/Store%2FSystemUpator%2FToDownload/raw?ref=83675d6cb628356ff11c9b366b0b23516ed9c206 (sorry if i responded to late, i was sleeping)

**Comment by GarboMuffin** [comment]
Ah, I see, we currently only allowed `*.gitlab.io` (GitLab Pages)

We'll add gitlab.com to the list too I suppose

**Comment by Mickmick21** [comment]
ah, also add extension.turbowarp.org, turbowarp.org as it prompts too.
