### ISSUE TITLE
two advice

### ISSUE THREAD

**Issue by qxsck** [TurboWarp/scratch-gui#723]
1. Display the "User ID" block and add customizations to it in "Edit".
2. Can set the display status for the building blocks, that is, change the properties of the block "shadow" in "project.json". It is can change it when you right-click of blocks. Hidden blocks can be displayed as translucent in TurboWarp.

**Comment by GarboMuffin** [comment]
I don't see any benefit of having user IDs in addition to usernames.

Hidden blocks are not an intended feature. You shouldn't use them.
