### ISSUE TITLE
Blank screen after refresh on Safari on iPadOS

### ISSUE THREAD

**Issue by DNin01** [TurboWarp/scratch-gui#730]
### Description

I decided to make a small project for fun today, so I opened TurboWarp, wrote some code, and saved my project. But then I refreshed the page and I was greeted with a white screen. After closing the tab, clearing (only) turbowarp.org website data and restarting my iPad, it would still show a blank page. However, updating my iPad to the latest release version resolved the issue and allowed the page to load again… until I refreshed it, then the same thing happened again.

Subdomains continue to load fine.

I’m not sure if this is a bug with Safari or with TurboWarp.

### Steps to Reproduce

1. Open TurboWarp
2. Open TurboWarp again

### Operating System and Browser

iPadOS 16.4, 16.4.1 / Safari

**Comment by Mickmick21** [comment]
that's a safari problem, Safari lacks of HTTP error handling

**Comment by DNin01** [comment]
It's working now, on iPadOS 16.5.1 (c)!
