### ISSUE TITLE
Block IDs in local project JSON and editor are inconsistent

### ISSUE THREAD

**Issue by ajskateboarder** [TurboWarp/scratch-gui#749]
I'm currently making an extension of TurboWarp through a user script that takes block IDs from a local project file and accesses blocks using those IDs in the editor. However, the project.json block IDs don't have consistent values.

Would it be possible to work around this?

**Comment by GarboMuffin** [comment]
this is because of block ID compression, which saves quite a bit of space in the project

**Comment by ajskateboarder** [comment]
> this is because of block ID compression, which saves quite a bit of space in the project

I know, but how come the editor and project use different block IDs? While the project.json uses the entire alphabet, the editor only utilizes a part of them

**Comment by ajskateboarder** [comment]
I've decided to use scratchblocks and `parse-sb3-blocks` to display modified blocks instead
