### ISSUE TITLE
Change the accent color to increase contrast

### ISSUE THREAD

**Issue by DNin01** [TurboWarp/scratch-gui#751]
As we come closer to Scratch's color update, I thought it might be a good idea for TurboWarp to have a color update too, so that it's more accessible as well.

I was thinking of something close to `hsl(343, 71%, 49%)`.

**Comment by Secret-chest** [comment]
Pink? Seriously?

**Comment by Secret-chest** [comment]
We need customisable colours first.

**Comment by GarboMuffin** [comment]
:tada: high contrast mode and a lot of other things have just been merged :tada:

**Comment by DNin01** [comment]
> :tada: high contrast mode and a lot of other things have just been merged :tada:

🎉

Haven't had a chance to check out all the changes and commits yet, but what would be cool is if high contrast mode darkened the TurboWarp red color, if the plan is to keep the current accent color in general.

**Comment by CST1229** [comment]
> Haven't had a chance to check out all the changes and commits yet, but what would be cool is if high contrast mode darkened the TurboWarp red color, if the plan is to keep the current accent color in general.

There are separate options for the accent and block colors, so if anything, a darker red would probably be added as a new accent color (or maybe instead as a "custom accent color" option).
![image](https://github.com/TurboWarp/scratch-gui/assets/68464103/374f45f9-3071-4fcc-a9ed-3f83a4544a6a)
