### ISSUE TITLE
Problem with "Costume editor snapping"

### ISSUE THREAD

**Issue by a-catgirl-dev** [TurboWarp/scratch-gui#752]
### Expected Behavior

When stage size is set larger than 480x360 (for this bug, i used 640x360) **while the "Costume editor snapping" extension is enabled**, snapping works as you intend to, on all sides.

### Actual Behavior

It won't let you snap to the right

### Steps to Reproduce

Enable costume editor snapping and set stage size to 640x360.

I have attached a video below

https://github.com/TurboWarp/scratch-gui/assets/75321465/b9f8af86-47c3-4e49-b02e-81f85ceaccc4

this also occurs on the desktop version.

### Operating System and Browser

Windows 10 on firefox 114.02

**Comment by CST1229** [comment]
I've found out that snapping at different stage sizes behaves like a 480x360 stage whose top left corner is at the actual stage top-left corner in the paint editor.

**Comment by BlueDome77** [comment]
bump
