### ISSUE TITLE
[COPYRIGHT CONCERN] Scratch cat in sprites

### ISSUE THREAD

**Issue by nmsderp** [TurboWarp/scratch-gui#754]
# Scratch cat in sprites
I searched up "cat" in the turbowarp sprite library and I saw this.
![Capture](https://github.com/TurboWarp/scratch-gui/assets/130254323/3efc37e3-b575-40af-ab76-32441b04e042)
I know the scratch cat is under copyright, so I don't know if it is aloud in turbowarp.
This is just me trying to tell you that the cat might need to be removed.

**Comment by CST1229** [comment]
1f018f59343e9d2808c81d9c3cec2df3bc40ad89

> This includes bringing back sprites that are Scratch trademarks.
> Basically:
>  - I don't believe including these in the library will be interpreted as an endorsement from Scratch
> - There is significant demand for these sprites
> - Scratch Addons uses the Scratch name and logo liberally and its store images contain the Scratch Cat but Scratch doesn't seem to care
> - I am entirely willing to remove them should Scratch ask me to
