### ISSUE TITLE
[BUG] unable to load scratch files on android 11

### ISSUE THREAD

**Issue by idoinfactexist** [TurboWarp/scratch-gui#822]
It sees the files but they're just shown as greyed out, same problem with packager as well
a mobile version of turbowarp would be great

**Comment by GarboMuffin** [comment]
This is a bug in Chrome on Android, we have changed literally nothing, nothing we can do.

Try this: https://www.reddit.com/r/GooglePixel/comments/15xut45/files_greyed_out/
