### ISSUE TITLE
I don't know what just happened.

### ISSUE THREAD

**Issue by familycomicsstudios** [TurboWarp/scratch-gui#823]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

well i'm on Opera GX on Windows, loaded a unsandboxed extension from an unsupported url, and this happened:
![image](https://github.com/TurboWarp/scratch-gui/assets/106832853/ad279db1-c82f-4309-b6f2-d160aea9398b)
anyone seen this before?

**Comment by GarboMuffin** [comment]
> loaded a unsandboxed extension from an unsupported url

Well then don't do that

**Comment by CommanderGL** [comment]
unsandboxed extensions do that sometimes
