### ISSUE TITLE
Ability to remove extensions

### ISSUE THREAD

**Issue by Aworldc** [TurboWarp/scratch-gui#833]
After adding an extension to a project, whether it's a scratch one or a turbowarp one, you cannot remove it, but instead have to make a new project and copy everything across

Especially with the large amounts of extensions getting added, it would be great if you can un-add extensions added to a project.

**Comment by LilyMakesThings** [comment]
Extensions are removed automatically if you don't use any blocks from the extension

**Comment by Aworldc** [comment]
Oh wow, i never noticed that before.

lol
