### ISSUE TITLE
Inconsistent orientation Turbowarp (web and desktop) vs Scratch

### ISSUE THREAD

**Issue by sfederici** [TurboWarp/scratch-gui#842]
Solicited by my students, I noticed just now (after two years...) that in Scratch projects where the orientation of my sprites is 90, when they are loaded in Turbowarp (both web and desktop versions) the orientations are changed to -270.

Whereas this is not a problem for how the projects behave (-270 is the same as 90) my students were puzzled and asked for an explanation. And when they open their projects in the other tool, they see this weird change-in-orientation-value behaviour.

Can someone tell me where could I modify the TW sourcecode so that every project where directions are less than -180 are mapped to positive directions? This is the most importanti info for me, as I'm running a customized desktop version, but if this could be changed even in the online version, it would be great.

**Comment by GarboMuffin** [comment]
We try to match Scratch, where are you seeing -270?

**Comment by GarboMuffin** [comment]
I am very sorry about all the delays getting responses, December is just a very bad time for me in general. Between this time next week and Christmas I will be more available

(you can faster responses through muffin@mailbox.org as those won't get buried in my GitHub notifications)

**Comment by CST1229** [comment]
> We try to match Scratch, where are you seeing -270?

I think this happens when you import a Scratch 1.4 project into 3.0 (or TW).

**Comment by sfederici** [comment]
> We try to match Scratch, where are you seeing -270?

For example in [this project](https://github.com/TurboWarp/scratch-gui/files/13657156/pong.sb3.zip) (sprites paddle, bottom, and bricks) NOTE: the project was originally created in Scratch 1.4 but then reworked many times in Scratch 3 and TW

**Comment by GarboMuffin** [comment]
Will be fixed when we finish merging >1yr of changes from Scratch, which is happening right now

**Comment by sfederici** [comment]
Excellent! Is it possible to know which are the changes, so that if I’m in trouble at recreating my custom version (that I hope not, but CS is always misterious) I can just import the ones that are relevant to me?

**Comment by GarboMuffin** [comment]
Here's the important change

https://github.com/scratchfoundation/scratch-vm/commit/2ae67598eebfa85ad6bf10b65325f0d70bdeb08e

you can apply those changes to the files in node_modules/scratch-vm/src/serialization

**Comment by sfederici** [comment]
I applied the changes to my custom TW and it worked quite well! Thanks a lot

**Comment by sfederici** [comment]
Proposed patch solved the problem
