### ISSUE TITLE
Scratch fullscreen working differently than Turbowarp fullscreen in macOS/Firefox

### ISSUE THREAD

**Issue by sfederici** [TurboWarp/scratch-gui#844]
### Expected Behavior

When the Scratch and Turbowarp windows are in fullscreen mode, they both show the greenflag, stop, no fullscreen buttons.

### Actual Behavior

In macOS, using fullscreen mode in Firefox, the projects gets the whole screenm without showing the greenflag, stop, no fullscreen buttons. This doesn't happen neither in Chrome and Safari on macoS nor on Windows. 

**NOTE: it would be cool to have the alternative to choose this "real" fullscreen mode in every browser and OS.**

### Steps to Reproduce

Open Scratch and Turbowarp in Firefox on macOS and go to fullscreen mode

### Operating System and Browser

Firefox 120.0.1 and macOS 14.1.1 (Sonoma)

**Comment by GarboMuffin** [comment]
Do you have the "Enhanced fullscreen" addon enabled only in Firefox perhaps?

**Comment by sfederici** [comment]
Sorry, I hadn’t noticed it. Thanks
