### ISSUE TITLE
Upcoming changes to usernames & cloud variables

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-gui#85]
## What's changing

TurboWarp's cloud variable server will be more enforcing significantly more strict restrictions on usernames.

It's not entirely clear what these restrictions are going to be yet, but it's expected that a significant portion (more than half) of custom usernames will no longer be valid.

These restrictions will be relaxed over time in a way that follows the Scratch Community Guidelines.

The reason I'm posting this here is because this will be a disruptive change and some of you will have to change your habits.

## Why

I've looked at the username logs. Too many people are using custom usernames for things that it was never intended to be used for, and the continuous effort of keeping word filters up-to-date is not something I want to continue. We try to follow the Scratch Community Guidelines around here, and that simply isn't possible without clamping down on custom usernames.

**Comment by LES-11** [comment]
fair enough

**Comment by Sylveon5** [comment]
Welp im the

**Comment by BioSniper123** [comment]
will the cloud variables be umped up,theres a 2.0 project that won't work

**Comment by GarboMuffin** [comment]
> 
> 
> will the cloud variables be umped up,theres a 2.0 project that won't work

Open a new issue with the project ID so I can look into it

**Comment by Xpexdex** [comment]
I just call myself Xpexdex on  turbowarp

**Comment by Tiber3333** [comment]
I call my self Tiber3333 on turbowarp. whats wrong with that?

**Comment by Tiber3333** [comment]
wait, I have an Idea! we can just log in to our scratch accounts on turbowarp.org! (only if we know the log in ID's)

**Comment by GarboMuffin** [comment]
> 
> 
> I just call myself Xpexdex on turbowarp

You will not be affected by these changes



> 
> 
> I call my self Tiber3333 on turbowarp. whats wrong with that?

Nothing, You will not be affected by these changes

> wait, I have an Idea! we can just log in to our scratch accounts on turbowarp.org! (only if we know the log in ID's)

not possible

**Comment by Tiber3333** [comment]
SO, you'll need to put in your password! you can't just put in your username.

**Comment by Tiber3333** [comment]
People can't just be griffpatch.

**Comment by Tiber3333** [comment]
> > I just call myself Xpexdex on turbowarp
> 
> You will not be affected by these changes
> 
> > I call my self Tiber3333 on turbowarp. whats wrong with that?
> 
> Nothing, You will not be affected by these changes
> 
> > wait, I have an Idea! we can just log in to our scratch accounts on turbowarp.org! (only if we know the log in ID's)
> 
> not possible

ok.

**Comment by Tiber3333** [comment]
![Screenshot 2021-03-12 at 13 25 58](https://user-images.githubusercontent.com/81035968/111877314-047b7e80-8960-11eb-80bc-07f8476f88b9.png)
Me.

**Comment by retronbv** [comment]
> SO, you'll need to put in your password! you can't just put in your username.

There is no way users will be inputting scratch passwords on turbowarp

**Comment by CST1229** [comment]
How about using something like FluffyScratch?
EDIT: To confirm your username is on Scratch and owned by you so it's all moderated by the ST.

**Comment by nova0x0** [comment]
why cant we have password authentication? like maybe you cant use a person on the scratch websites name unless you log in as them?

**Comment by nova0x0** [comment]
that would also open the possibility to use scratch's cloud variable server if a registered scratcher!

**Comment by GarboMuffin** [comment]
> 
> 
> why cant we have password authentication? like maybe you cant use a person on the scratch websites name unless you log in as them?
> 
> 
> that would also open the possibility to use scratch's cloud variable server if a registered scratcher!

you're essentially asking me to build a phishing website for Scratch accounts... not happening

Right now the plan is to essentially only allow custom usernames if there is a Scratch account with that username. This will do a lot to reduce the amount of problematic usernames and people trying to chat with eachother.

I don't think impersonation is a huge deal right now and any solution to that will be very complex for people to understand. It can be resolved when it becomes an issue.

**Comment by LES-11** [comment]
> I don't think impersonation is a huge deal right now and any solution to that will be very complex for people to understand. It can be resolved when it becomes an issue.

One possible solution could be using something along the lines of Scratch Verifier.
Here are a couple of links you could look into, I'm not sure how secure they are but it is something that can be looked into.
https://github.com/ScratchVerifier/ScratchVerifier
https://github.com/micahlt/sv2

(I'm just brainstorming for th future here, it is completely up to you.)

**Comment by Spirit-Ignited** [comment]
okay how about you only allow for usernames that exist on scratch + get a massive wordlist for now (i have one on my scratch acc spirit-ignited)

**Comment by Spirit-Ignited** [comment]
this would do for now until we get an actual solution

**Comment by Spirit-Ignited** [comment]
can you work with the ST?

**Comment by SelixGithub** [comment]
makes sense :)

**Comment by Spirit-Ignited** [comment]
actually just create a code that runs every week and gets the usernames of all scratchers who are neither banned nor deleted, and this will be the whitelist for the week (/fortnight /month /any amount of time)

**Comment by Admin-system-scratch** [comment]
Hey GarboMuffin uh I was banned by a Scratch team member in scratch for telling the truth
 @GarboMuffin it's a Bad Idea to WhiteList Usernames And maybe you could just make A login in [TurboWarp](https://turbowarp.org/) That does not connect scratch accounts :)

Thank you for Bringing Us [TurboWarp](https://turbowarp.org/) :) Without that people can never scratch 
while I was gone I got hooked to coding and made a game GarboMuffin Still working on it 
Can you Please Upload a Code I need for the cloud variable Save username list

**Comment by ego-lay-atman-bay** [comment]
> actually just create a code that runs every week and gets the usernames of all scratchers who are neither banned nor deleted, and this will be the whitelist for the week (/fortnight /month /any amount of time)

why? When you enter a username, it can just check for the username on scratch, see if it's not banned or deleted, and then if it exists, it'll accept it. No need to create a whitelist.

**Comment by BioSniper123** [comment]
my username is BioSniper123,would that be banned?

**Comment by GarboMuffin** [comment]
If your TurboWarp username is the same thing as your Scratch username, there is a very high chance you will be perfectly fine (nearly a guarantee)

**Comment by lisa-wolfgang** [comment]
> Right now the plan is to essentially only allow custom usernames if there is a Scratch account with that username. This will do a lot to reduce the amount of problematic usernames and people trying to chat with each other.

So the default username (generated on page load) won't be affected by this, right?

**Comment by Dieforrobux** [comment]
> SO, you'll need to put in your password! you can't just put in your username.

No way. that would need something to track down every scratch user.

**Comment by FunctionalMetatable** [comment]
I feel its better to use fluffyscratch for custom usernames, if the user wants to change it, and the default would be player<NUMBER>

**Comment by GarboMuffin** [comment]
It appears this issue has become a bit noisy. If you have any thoughts/questions whatever then go to https://github.com/TurboWarp/scratch-gui/discussions or https://scratch.mit.edu/users/GarboMuffin/#comments

> So the default username (generated on page load) won't be affected by this, right?

Random `player1234` usernames will be not affected.

Impersonation has come up a few times in here, and I still don't think it's a widespread issue, but a warning will be added explaining how cloud variables work in TW and explain that username ownership is not checked.

I looked at the logs again and the impact of these changes seems to be much smaller than I expected, probably because of weekend vs weekday traffic. Anways the changes go live tomorrow.
