### ISSUE TITLE
Some blocks aren't very legible in high contrast mode

### ISSUE THREAD

**Issue by DNin01** [TurboWarp/scratch-gui#866]
TurboWarp automatically adjusts the colors of blocks in high contrast mode, but it could be better on very light or dark blocks.

Most importantly, very dark blocks are completely illegible as they aren't really brightened that much at all.

Some of the blocks probably don't have to be quite as light in high contrast mode as they are currently (too much luminance difference and they seem off from their default colors).

![TurboWarp-exclusive blocks in default colors](https://github.com/TurboWarp/scratch-gui/assets/106490990/4ce8dec2-a21d-4f2b-b9c7-fcb1c3628c8b) ![TurboWarp-exclusive blocks in high-contrast colors](https://github.com/TurboWarp/scratch-gui/assets/106490990/e86fd05f-b356-4fbb-8192-70ac53788985)

The luminance should at least be boosted below some point and increased in general.

Remember that the luminance difference can be quite different than the actual perceived contrast, as [Myndex has figured out](https://www.myndex.com/APCA/).

**Comment by GarboMuffin** [comment]
https://github.com/TurboWarp/scratch-gui/blob/develop/src/lib/themes/blocks/high-contrast.js#L115

open to improvements on that

**Comment by GarboMuffin** [comment]
old:

![image](https://github.com/TurboWarp/scratch-gui/assets/33787854/d3a031e1-8e64-4758-891a-ec1af7977718)

new:

![image](https://github.com/TurboWarp/scratch-gui/assets/33787854/ce82a7e6-0983-4eb7-8084-0363083e8502)
