### ISSUE TITLE
Freezing and crashing on chrome

### ISSUE THREAD

**Issue by LIZARD-OFFICIAL** [TurboWarp/scratch-gui#870]
Recently I switched from opera gx (due to privacy/security concerns) to google chrome, and turbowarp.org keeps crashing both on my phone and my pc when using chrome. It just says page unresponsive and crashes for no actual reason.

Ok this breaks on all browsers - https://turbowarp.org/950701969

**Comment by GarboMuffin** [comment]
try advanced > turn on warp timer

off topic: switching from opera to chrome for privacy reasons is kinda funny. you just replaced opera with google. maybe you're more okay with that, but it's still not great

**Comment by LIZARD-OFFICIAL** [comment]
Google doesn't send as much info as gx, gx sells info to china which is much more concerning.

**Comment by yuri-kiss** [comment]
> Google doesn't send as much info as gx, gx sells info to china which is much more concerning.

there is still other browsers lol

**Comment by LIZARD-OFFICIAL** [comment]
yea i swtiched to firefox, btw the bug can be fixed using "Warp Timer"
