### ISSUE TITLE
Scratch.canFetch()がsandbox環境だとtrueを返す

### ISSUE THREAD

**Issue by arch-herobrine** [TurboWarp/scratch-gui#883]
再現方法
[これ](https://arch-herobrine.github.io/tools/fetch-extra.js)で外部サイトをfetchしようとする

**Comment by arch-herobrine** [comment]
(日本語ですいません)

**Comment by T-taku** [comment]
こんにちは、このバグについて詳しく教えていただけますか？英語に翻訳します。

**Comment by arch-herobrine** [comment]
えーっと
サンドボックス化を無効化すると
なぜか普通にfetchが通ってしまうんですよね
なので「fetchを許可しますか」的なポップアップなしでそのまま外部と通信できてしまうっていう

**Comment by GarboMuffin** [comment]
It's not enforced in the 'sandbox' because you can bypass it by simply using window.fetch

canFetch requires trust that the extension won't do that. If an extension runs in the sandbox then it is not trusted.

**Comment by arch-herobrine** [comment]
タイトルミスってたっぽいかな
けっこう前に開いたissueだから覚えてないや

> It's not enforced in the 'sandbox' because you can bypass it by simply using window.fetch
> 
> canFetch requires trust that the extension won't do that. If an extension runs in the sandbox then it is not trusted.

**Comment by arch-herobrine** [comment]
ミスってはいなかったわ
