### ISSUE TITLE
here you go

### ISSUE THREAD

**Issue by BioSniper123** [TurboWarp/scratch-gui#89]
> 
> 
> will the cloud variables be umped up,theres a 2.0 project that won't work

Open a new issue with the project ID so I can look into it

_Originally posted by @GarboMuffin in https://github.com/TurboWarp/scratch-gui/issues/85#issuecomment-803334693_

**Comment by BioSniper123** [comment]
46587498 is the ID,it brakes when another player joins

**Comment by GarboMuffin** [comment]
It should work now
