### ISSUE TITLE
Switch to AGPL to prevent nonfree forks from appearing

### ISSUE THREAD

**Issue by Secret-chest** [TurboWarp/scratch-gui#898]
Gandi IDE is an example.

**Comment by GarboMuffin** [comment]
The editor is already GPL, hence they did not use anything from our editor (except an old non-GPL version of -paint). AGPL would not change anything there. The things involved in project running itself are not GPL because that would make packaging non-GPL projects using the packager impossible.

**Comment by GarboMuffin** [comment]
Do you have a reason why you think AGPL would be preferable over GPL for the editor?

**Comment by Secret-chest** [comment]
Then you can change the compiler to LGPL, which allows linking with other licences but forbids relicensing the code itself.

With GPL you can host a program on your public server and keep it nonfree because it is not sharing. With AGPL hosting is sharing.

**Comment by GarboMuffin** [comment]
https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic

I think I used to think that statically-linked-LGPL (what the packager would do) was effectively GPL but that seems to not be the case

I really don't see how the AGPL would matter for scratch-gui and friends but it can be looked at

**Comment by GarboMuffin** [comment]
If we switch to AGPL then we would also want eg. Scratch Addons to do the same, otherwise it might be a bit harder to send patches back upstream there

**Comment by GarboMuffin** [comment]
vm, render, packager, some extensions are now LGPL-3.0 moving forward

gui, addons, blocks, paint, desktop were already GPL-3.0

some very small libraries and parts of scratch that we've made only small changes to are still permissive as it is not worth the trouble and a lot of those have a lot of replacements already

backend stuff remains permissive as most of that is a disaster anyways and there's very simple replacements for all of that already

**Comment by DNin01** [comment]
@GarboMuffin Scratch is now [moving to AGPL-3.0](https://www.scratchfoundation.org/open-source-license), so I guess we'll be doing that too.

We should especially consider how this will affect not only the main TurboWarp editor but also `packager` and `extensions`.

**Comment by GarboMuffin** [comment]
It is inevitable that TurboWarp/scratch-gui and TurboWarp/desktop is going AGPL

What happens to the rest, is not clear yet, and it is possible I talk to a lawyer ahead of time
