### ISSUE TITLE
Unable to use project_url paramater

### ISSUE THREAD

**Issue by snowboyz0825** [TurboWarp/scratch-gui#902]
Whenever I attempt to embed a project, it throws this error - "TypeError: Failed to fetch
Component stack: in vI in Connect(vI) ..."
I believe I may be typing it wrong or possibly using an incorrect link, but I have tried
https://github.com/snowboyz0825/snowscodestuff/raw/main/SB3s/Dodge+the+Dots.sb3/ which should be a direct download link
and
https://drive.usercontent.google.com/u/0/uc%3Fid%3D10hagaW-5nqktABP3TjSVUG-gXdPSUFgK&export=download
which likely has some security, but I did set it to public

Likely important to mention that the links are 
https://turbowarp.org/?project_url=https://github.com/snowboyz0825/snowscodestuff/blob/main/SB3s/Dodge+the+Dots.sb3
https://turbowarp.org/?project_url=https://https://github.com/snowboyz0825/snowscodestuff/raw/main/SB3s/Dodge%20the%20Dots.sb3
https://turbowarp.org/?project_url=https://drive.usercontent.google.com/u/0/uc%3Fid%3D10hagaW-5nqktABP3TjSVUG-gXdPSUFgK&export=download

### Expected Behavior

Should fetch the file and use it.

### Actual Behavior

Fails to load and gives the error "TypeError: Failed to fetch
Component stack: in vI in Connect(vI) ..."

### Steps to Reproduce

Simply attempt to use the "Project _url" paramater as described in the [Turbowarp Documentation](https://docs.turbowarp.org/url-parameters)

### Operating System and Browser

ChromeOS/Chrome ver, 121.0.6167.188

**Comment by GarboMuffin** [comment]
https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

If you click on the raw button on GitHub **and copy the URL that it redirects to** (the link will be on raw.githubusercontent.com), those URLs should work.
