### ISSUE TITLE
Running in gitpod

### ISSUE THREAD

**Issue by veggiecan0419** [TurboWarp/scratch-gui#905]
Hi everyone,

When I try to start the development server on gitpod it just opens up a page which says `invalid host header`.
How can I fix that?

**Comment by GarboMuffin** [comment]
I'm unable to help with anything that isn't running locally on your computer

**Comment by GarboMuffin** [comment]
See if this helps? https://stackoverflow.com/questions/43619644/i-am-getting-an-invalid-host-header-message-when-connecting-to-webpack-dev-ser

**Comment by veggiecan0419** [comment]
@GarboMuffin 
I figured it out.
You just need to add 
```javascript
disableHostCheck: true,
```
to the `devServer` section in `webpack.config.js` and then it works

**Comment by GarboMuffin** [comment]
Let's leave this open since we can probably just make that the default
