### ISSUE TITLE
'is compiled?' equivalent for screen resolution.

### ISSUE THREAD

**Issue by Tacodiva** [TurboWarp/scratch-gui#91]
Is there an equivalent to the ''is compiled?" block to get screen resolution. This would be really useful for supporting large screens otherwise vanilla scratch projects.
_Edit:_ Realizing I probably should have submitted this issue under TurboWarp/scratch-vm

**Comment by GarboMuffin** [comment]
https://scratch.mit.edu/projects/475562469/
