### ISSUE TITLE
Tubrowarp Project Screen White Screen

### ISSUE THREAD

**Issue by Minecraft3193092** [TurboWarp/scratch-gui#920]
### Actual Behavior
log : [turbowarp.org-1713079950903.log](https://github.com/TurboWarp/scratch-gui/files/14969849/turbowarp.org-1713079950903.log)
[turbowarp.org-1713079943703.log](https://github.com/TurboWarp/scratch-gui/files/14969850/turbowarp.org-1713079943703.log)
### Steps to Reproduce
to https://www.Turbowarp.org

### Operating System and Browser

Windows 11 Chorme 123.0.6312.107

**Comment by GarboMuffin** [comment]
Uninstall "WebGLRipper". It is breaking the website.

**Comment by GarboMuffin** [comment]
I reported it to the webglripper people but really just uninstall it / turn it off / disable "Shader Calc". It is not our bug and we will not be fixing it. (instead we will throw up a big non-ignorable error message)
