### ISSUE TITLE
Project does not render properly on BlissOS

### ISSUE THREAD

**Issue by snowboyz0825** [TurboWarp/scratch-gui#921]
### Expected Behavior

Renders properly

### Actual Behavior

![Screenshot_20240414-112537_Chrome](https://github.com/TurboWarp/scratch-gui/assets/101284660/8c85b3a8-a96a-49bd-b8e7-cec4fe264706)

_Describe what actually happens_

![Screenshot_20240414-112537_Chrome](https://github.com/TurboWarp/scratch-gui/assets/101284660/ee15570a-e4d1-47f6-93af-9c55c485d917)

### Steps to Reproduce

Install BlissOS and try to use turbowarp on chrome. I suspect it's some issue without having FFMPEG or something similair, I will try with other BlissOS settings and see what happens

Normal - Rendering is skewed and wrong
w/ FFMPEG - Same Issue
PC Mode - Same Issue
PC Mode w/ FFMPEG -

### Operating System and Browser

BlissOS 15.9 (I believe it's based on google pixel tablets (?), also based in android 12), Chrome for Android

**Comment by snowboyz0825** [comment]
I wrote lots about the issue, but found it was a problem on chrome, and using DuckDuckGo fixed it. I accidentally refreshed, but I will be marking this as resolved as I have solved the issue.

**Comment by GarboMuffin** [comment]
In the future I will note that graphical errors like that are almost always a browser/GPU driver bug which we usually can't help much with, especially on a niche platform like BlissOS

(In the past we've done full dot-releases to workaround bugs in the Linux graphics stack but that was an exceptional case where it was broken for a lot of people in a reproducible way, and I happen to use Linux every day)
