### ISSUE TITLE
'When This Sprite Clicked' Event Block Broken- Not able to take Sprite Click on Stage

### ISSUE THREAD

**Issue by SparkScratch-P** [TurboWarp/scratch-gui#928]
### Expected Behavior

_When a sprite, with 'This Sprite is CLicked', The Sprite should take a click and execute its code._

### Actual Behavior

_When a sprite, with the 'This Sprite is CLicked' event block, on stage, is clicked, it takes no response!_

### Steps to Reproduce

_Take a sprite and code, the "When this Sprite CLicked" event block, and give it a task, like 'Say Hello for 2 Sec" from the Looks.  Then, Click on the particular sprite on stage. Nothing Happens!_

### Operating System and Browser

_Windows 10, Chrome_

**Comment by GarboMuffin** [comment]
can not reproduce, please provide example project file

**Comment by SparkScratch-P** [comment]
[Project2.zip](https://github.com/TurboWarp/scratch-gui/files/15238970/Project2.zip)

## Just have a look. I am trying to click the sprites on stage, but it is not being clicked. The same problem persists even on packaging.

**Comment by GarboMuffin** [comment]
You have an iframe covering the entire page. Turn off interactivity with this block to allow clicking behind it:


![image](https://github.com/TurboWarp/scratch-gui/assets/33787854/9d8de047-7cc4-4353-b0b0-e1acfe703080)

or make the frame smaller; point is you either can click on the iframe or the stage, not both. We can't change that

**Comment by SparkScratch-P** [comment]
Oh, ok thanks, but to inform you - I had to use the iframe because the POST in HTML Request was not working. The GET type request is working, but not the POSTs.
